---
title: "Descriptive part 1"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r, include=FALSE}
theme_park = read_csv("ultimate data.csv") |> 
    mutate(
    Year = as.factor(Year)
  ) 
```

## Summary: Total Attendance by Type
```{r region attend summary}
theme_park  |> 
    filter(
      Region != c("Worldwide")
    ) |> 
    group_by(Year, Type) |> 
    mutate(
      Attendance = Attendance / 100000
    ) |> 
    summarise(sum = sum(Attendance)) |> 
    arrange(Type) |> 
    pivot_wider(
      names_from = Type,
      values_from = sum
    ) |> 
    knitr::kable(digits = 3, caption = c("Summary of Attendance for Three Types of Facilities From 2019 to 2022"))
```



```{r}
theme_park |> 
  group_by(Year) |> 
  plot_ly(y = ~Attendance, color = ~Year, type = "box", colors = "viridis")
```



```{r}
 theme_park|> 
  filter(
    Region != c("Worldwide")
  ) |> 
  group_by(Region, Year)  |> 
  summarize(attend_sum = mean(Attendance)) |> 
  plot_ly(x = ~Year, y = ~attend_sum, color = ~Region,
          type = "scatter", mode = 'point', colors = "viridis")
```

## ANOVA TEST BY TYPE

```{r}
theme_park_anova = 
  theme_park |> 
  filter(
    Region != c("Worldwide")
  ) |> 
  mutate(
    Type = as.factor(Type)
  )

anova_1 = aov(Attendance ~ Type, data = theme_park_anova) |> summary()

```


