<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Impact of the Pandemic on the Attendance of Theme Parks/Museums Worldwide</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="final_report.html">Final Report</a>
</li>
<li>
  <a href="Data-Collection_Updated.html">Data Collection</a>
</li>
<li>
  <a href="theme_zz.html">EDA</a>
</li>
<li>
  <a href="Regression.html">Regression</a>
</li>
<li>
  <a href="mailto:&lt;yy3421@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/yilei-y/theme_park.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Impact of the Pandemic on the Attendance of
Theme Parks/Museums Worldwide</h1>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>As theme parks and museums are significant contributors to the
tourism and entertainment industry. Then understanding how attendance
has been affected is vital and may provides insights into the economic
impact of the pandemic on these sectors. </p>
<p>In addition, analyzing attendance data of parks and museums from
different region can provide insights into how the impact of the
pandemic on theme parks and museums in the United States compares to
other countries. This comparative analysis helps in understanding the
global dynamics of the tourism and entertainment industries, which also
provides insights into understanding how different regions responded to
COVID-19.</p>
</div>
<div id="related-work" class="section level2">
<h2>Related work</h2>
<p>The official websites of major theme park operators release
statements and reports on how the pandemic has affected their attendance
and operations, which inspire us to investigate the impact of the
COVID-19 pandemic on theme park attendance.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial questions</h2>
<p>The main question we are trying to understand is what is the overall
Impact of the COVID-19 Pandemic on Theme Park Attendance. While
collecting the data, we also involved attendance data of different theme
parks, water parks and museums around the world. After adding variables
such as park types and regions, we also tried to investigate the
relationship between the park attendance and other covariants.</p>
</div>
<div id="data-collection-and-cleaning" class="section level2">
<h2>Data Collection and cleaning</h2>
<div id="data-collection-and-data-source" class="section level3">
<h3>Data Collection and Data Source</h3>
<p>We sourced our data from the <em>“Global Attractions Attendance
Report”</em>, a publication by AECOM and TEA. The dataset comprises
attendance information for various theme parks and museums worldwide,
covering the years 2019 to 2022. You can access the detailed report
through this <a
href="https://aecom.com/wp-content/uploads/documents/reports/AECOM-Theme-Index-2022.pdf">link</a>.</p>
</div>
<div id="data-import-and-cleaning" class="section level3">
<h3>Data Import and Cleaning</h3>
<p>Each individual dataset catgegorized by types of parks and regions of
the parks are listed in the article. By collecting each of the dataset,
we created separate dataframes and combine to one ultimate dataset with
all of the data focusing on <code>Park_Name</code>, <code>City</code>,
<code>Country</code>, <code>Year</code>, <code>Attendance</code>,
<code>Type</code>, and <code>Region</code>.</p>
<ul>
<li><code>Park_Name</code>: Names of the park</li>
<li><code>City</code>: City of where the park is located</li>
<li><code>Country</code>: Country of where the park is located</li>
<li><code>Year</code>: Year of attendance</li>
<li><code>Attendance</code>: Number of people visited the park</li>
<li><code>Type</code>: Amusement/Theme Parks, Water Parks, and
Museums</li>
<li><code>Region</code>: Worldwide, North America, Latin America, Asia
Pacific, Europe Middle East Africa</li>
</ul>
<div id="import-the-amusementtheme-parks-data-of-worldwide-2019-2022"
class="section level4">
<h4>Import the amusement/theme parks data of Worldwide 2019-2022</h4>
<pre class="r"><code>data_text_tp_ww = &quot;1, MAGIC KINGDOM THEME PARK AT WALT DISNEY WORLD RESORT, LAKE BUENA VISTA, U.S., 35%, 17133, 12691, 6941, 20963
2, DISNEYLAND PARK AT DISNEYLAND RESORT, ANAHEIM, U.S., 97%, 16881, 8573, 3674, 18666
3, TOKYO DISNEYLAND AT TOKYO DISNEY RESORT, TOKYO, JAPAN, 90%, 12000, 6300, 4160, 17910
4, TOKYO DISNEYSEA AT TOKYO DISNEY RESORT, TOKYO, JAPAN, 74%, 10100, 5800, 3400, 14650
5, UNIVERSAL STUDIOS JAPAN, OSAKA, JAPAN, 125%, 12350, 5500, 4901, 14500
6, DISNEY&#39;S ANIMAL KINGDOM AT WALT DISNEY WORLD, LAKE BUENA VISTA, U.S., 25%, 9027, 7194, 4166, 13888
7, EPCOT AT WALT DISNEY WORLD, LAKE BUENA VISTA, U.S., 29%, 10000, 7752, 4044, 12444
8, CHIMELONG OCEAN KINGDOM, HENGQIN, CHINA, -41%, 4400, 7452, 4797, 11736
9, DISNEY&#39;S HOLLYWOOD STUDIOS AT WALT DISNEY WORLD, LAKE BUENA VISTA, U.S., 27%, 10900, 8589, 3675, 11483
10, SHANGHAI DISNEYLAND AT SHANGHAI DISNEY RESORT, SHANGHAI, CHINA, -38%, 5300, 8480, 5500, 11210
11, UNIVERSAL STUDIOS FLORIDA AT UNIVERSAL ORLANDO, FL, U.S., 20%, 10750, 8987, 4096, 10922
12, UNIVERSAL&#39;S ISLANDS OF ADVENTURE AT UNIVERSAL ORLANDO, ORLANDO, U.S., 21%, 11025, 9077, 4005, 10375
13, DISNEYCALIFORNIA ADVENTURE PARK AT DISNEYLAND RESORT, ANAHEIM, U.S., 81%, 9000, 4977, 1919, 9861
14, DISNEYLAND PARK AT DISNEYLAND PARIS, MARNE-LA-VALLEE, FRANCE, 184%, 9930, 3500, 2620, 9745
15, UNIVERSAL STUDIOS HOLLYWOOD, UNIVERSAL CITY, U.S., 53%, 8400, 5505, 1299, 9147
16, EVERLAND, GYEONGGI-DO, SOUTH KOREA, 56%, 5770, 3710, 2760, 6606
17, LOTTE WORLD, SEOUL, SOUTH KOREA, 84%, 4520, 2460, 1560, 5953
18, NAGASHIMA SPA LAND, KUWANA, JAPAN, 17%, 4200, 3600, 2400, 5950
19, EUROPA-PARK, RUST, GERMANY, 100%, 6000, 3000, 2500, 5750
20, OCEAN PARK, HONG KONG, SAR, 0%, 1400, 1400, 2200, 5700
21, HONG KONG DISNEYLAND, HONG KONG, SAR, 21%, 3400, 2800, 1700, 5695
22, DE EFTELING EFTELING THEME PARK RESORT, KAATSHEUVEL, NETHERLANDS, 65%, 5430, 3300, 2900, 5260
23, WALT DISNEY STUDIOS PARK AT DISNEYLAND PARIS, MARNE-LA-VALLEE, FRANCE, 183%, 5340, 1884, 1410, 5245
24, OCT HAPPY VALLEY, BEIJING, CHINA, -24%, 3740, 4930, 3950, 5160
25, CHIMELONG PARADISE, GUANGZHOU, CHINA, -41%, 2300, 3890, 2681, 4905&quot;

top25_tp_ww = read.table(text = data_text_tp_ww, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top25_tp_ww) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-25-amusementtheme-parks-worldwide-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 25 amusement/theme parks Worldwide in
2019 to 2022</h4>
<pre class="r"><code>top25_tp_ww_clean_df =
  top25_tp_ww |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Amusement/Theme Park&quot;,
    Region = &quot;Worldwide&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div
id="import-the-amusementtheme-parks-data-of-north-america-2019-2022"
class="section level4">
<h4>Import the amusement/theme parks data of North America
2019-2022</h4>
<pre class="r"><code>data_text_tp_na = &quot;1, MAGIC KINGDOM THEME PARK AT WALT DISNEY WORLD, LAKE BUENA VISTA, FL, U.S., 35%, 17133, 12691, 6941, 20963
2, DISNEYLAND PARK AT DISNEYLAND RESORT, ANAHEIM, CA, U.S., 97%, 16881, 8573, 3674, 18666
3, DISNEY&#39;S ANIMAL KINGDOM AT WALT DISNEY WORLD, LAKE BUENA VISTA, FL, U.S., 25%, 9027, 7194, 4166, 13888
4, EPCOT AT WALT DISNEY WORLD, LAKE BUENA VISTA, FL, U.S., 29%, 10000, 7752, 4044, 12444
5, DISNEY&#39;S HOLLYWOOD STUDIOS AT WALT DISNEY WORLD, LAKE BUENA VISTA, FL, U.S., 27%, 10900, 8589, 3675, 11483
6, UNIVERSAL STUDIOS FLORIDA, ORLANDO, FL, U.S., 20%, 10750, 8987, 4096, 10922
7, UNIVERSAL&#39;S ISLANDS OF ADVENTURE, ORLANDO, FL, U.S., 21%, 11025, 9077, 4005, 10375
8, DISNEY CALIFORNIA ADVENTURE PARK AT DISNEYLAND RESORT, ANAHEIM, CA, U.S., 81%, 9000, 4977, 1919, 9861
9, UNIVERSAL STUDIOS HOLLYWOOD, UNIVERSAL CITY, CA, U.S., 53%, 8400, 5505, 1299, 9147
10, SEAWORLD ORLANDO, ORLANDO, FL, U.S., 46%, 4454, 3051, 1598, 4640
11, KNOTT&#39;S BERRY FARM, BUENA PARK, CA, U.S., 6%, 3899, 3681, 811, 4238
12, BUSCH GARDENS TAMPA BAY, TAMPA, FL, U.S., 26%, 4051, 3210, 1288, 4180
13, CANADA&#39;S WONDERLAND, MAPLE, ONTARIO, CANADA, 524%, 3768, 587, 0, 3950
14, SEAWORLD SAN DIEGO, SAN DIEGO, CA, U.S., 25%, 3507, 2800, 1139, 3731
15, CEDAR POINT, SANDUSKY, OH, U.S., 4%, 3444, 3327, 1020, 3610
16, SIX FLAGS MAGIC MOUNTAIN, VALENCIA, CA, U.S., -2%, 2993, 3047, 686, 3521
17, KINGS ISLAND, KINGS ISLAND, OH, U.S., 5%, 3340, 3181, 1626, 3485
18, SIX FLAGS GREAT ADVENTURE, JACKSON, NJ, U.S., -26%, 2153, 2913, 598, 3451
19, HERSHEYPARK, HERSHEY, PA, U.S., 6%, 3193, 3012, 1717, 3384
20, SIX FLAGS GREAT AMERICA, GURNEE, IL, U.S., -5%, 2535, 2675, 0, 3169&quot;

top20_tp_na = read.table(text = data_text_tp_na, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;)
colnames(top20_tp_na) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;State&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-amusementtheme-parks-north-america-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 amusement/theme parks North America
in 2019 to 2022</h4>
<pre class="r"><code>top20_tp_na_clean_df =
  top20_tp_na |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Amusement/Theme Park&quot;,
    Region = &quot;North America&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div
id="import-the-amusementtheme-parks-data-of-latin-america-2019-2022"
class="section level4">
<h4>Import the amusement/theme parks data of Latin America
2019-2022</h4>
<pre class="r"><code>data_text_tp_la = &quot;1,SIX FLAGS MEXICO, MEXICO CITY, MEXICO, 54%, 1727, 1125, 701, 2803
2,BETO CARRERO WORLD, SANTA CATARINA, BRAZIL, 23%, 2327, 1895, 1252, 2241
3,PARQUE XCARET, CANCUN, MEXICO, 27%, 1399, 1104, 736, 1960
4,MUNDO PETAPA, GUATEMALA CITY, GUATEMALA, 99%, 800, 402, 268, 1330
5,LA FERIA DE CHAPULTEPEC, MEXICO CITY, MEXICO, 0%, 0, 0, 0, 1306
6,PLAZA DE SESAMO, MONTERREY, MEXICO, 0%, 0, 0, 0, 1173
7,PARQUE MUNDO AVENTURA, BOGOTÁ, COLOMBIA, 19%, 752, 631, 344, 1151
8,FANTASIALANDIA, SANTIAGO, CHILE, 38%, 850, 615, 430, 1100
9,THEME PARQUE NACIONAL DEL CAFÉ, QUINDIO, COLOMBIA, 30%, 626, 482, 321, 1043
10,PARQUE DE LA COSTA, BUENOS AIRES, ARGENTINA, 30%, 514, 395, 263, 968&quot;

top10_tp_la = read.table(text = data_text_tp_la, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;)
colnames(top10_tp_la) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-10-amusementtheme-parks-latin-america-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 10 amusement/theme parks Latin America
in 2019 to 2022</h4>
<pre class="r"><code>top10_tp_la_clean_df =
  top10_tp_la |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Amusement/Theme Park&quot;,
    Region = &quot;Latin America&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-the-amusementtheme-parks-data-of-asia-pacific-2019-2022"
class="section level4">
<h4>Import the amusement/theme parks data of Asia Pacific 2019-2022</h4>
<pre class="r"><code>data_text_tp_apac = &quot;1, TOKYO DISNEYLAND AT TOKYO DISNEY RESORT, TOKYO, JAPAN, 90%, 12000, 6300, 4160, 17910
2, TOKYO DISNEYSEA AT TOKYO DISNEY RESORT, TOKYO, JAPAN, 74%, 10100, 5800, 3400, 14650
3, UNIVERSAL STUDIOS JAPAN, OSAKA, JAPAN, 125%, 12350, 5500, 4901, 14500
4, CHIMELONG OCEAN KINGDOM, HENGQIN, CHINA, -41%, 4400, 7452, 4797, 11736
5, SHANGHAI DISNEYLAND AT SHANGHAI DISNEY RESORT, SHANGHAI, CHINA, -38%, 5300, 8480, 5500, 11210
6, EVERLAND, SEOUL, SOUTH KOREA, 56%, 5770, 3710, 2760, 6606
7, LOTTE WORLD, SEOUL, SOUTH KOREA, 84%, 4520, 2460, 1560, 5953
8, NAGASHIMA SPA LAND, KUWANA, JAPAN, 17%, 4200, 3600, 2400, 5950
9, OCEAN PARK, HONG KONG, SAR, 0%, 1400, 1400, 2200, 5700
10, HONG KONG DISNEYLAND, HONG KONG, SAR, 21%, 3400, 2800, 1700, 5695
11, OCT HAPPY VALLEY, BEIJING, CHINA, -24%, 3740, 4930, 3950, 5160
12, CHIMELONG PARADISE, GUANGZHOU, CHINA, -41%, 2300, 3890, 2681, 4905
13, UNIVERSAL STUDIOS SINGAPORE, Sentosa, SINGAPORE, 75%, 2100, 1200, 1098, 4500
14, CHINA DINOSAUR PARK, CHANGZHOU, CHINA, -12%, 2200, 2500, 2375, 4434
15, OCT WINDOW OF THE WORLD, SHENZHEN, CHINA, -54%, 1100, 2400, 1890, 3990
16, OCT HAPPY VALLEY, SHENZHEN, CHINA, -47%, 1750, 3310, 3120, 3980
17, ZHENGZHOU FANTAWILD ADVENTURE, ZHENGZHOU, CHINA, -42%, 1590, 2752, 3421, 3840
18, OCT HAPPY VALLEY, CHENGDU, CHINA, -47%, 1570, 2940, 2620, 3580
19, NINGBO FANTAWILD ORIENTAL HERITAGE, NINGBO, CHINA, -47%, 1230, 2308, 2257, 3575
20, OCT HAPPY VALLEY, SHANGHAI, CHINA, -62%, 1240, 3300, 2730, 3390&quot;

top20_tp_apac = read.table(text = data_text_tp_apac, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_tp_apac) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-of-the-top-20-amusementtheme-parks-asia-pacific-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset of the top 20 Amusement/Theme Parks Asia Pacific
in 2019 to 2022</h4>
<pre class="r"><code>top20_tp_apac_clean_df =
  top20_tp_apac |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2021&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Amusement/Theme Park&quot;,
    Region = &quot;Asia Pacific&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div
id="import-the-amusementtheme-parks-data-of-europe-middle-east-africa"
class="section level4">
<h4>Import the amusement/theme parks data of Europe Middle East
Africa</h4>
<pre class="r"><code>data_text_tp_emea = &quot;1,DISNEYLAND PARK AT DISNEYLAND PARIS, MARNE-LA-VALLEE, FRANCE,184%,9930,3500,2620,9745
2,EUROPA-PARK, RUST, GERMANY,80%,5400,3000,2500,5750
3,DE EFTELING THEME PARK RESORT, KAATSHEUVEL, NETHERLANDS,65%,5430,3300,2900,5260
4,WALT DISNEY STUDIOS PARK AT DISNEYLAND PARIS, MARNE-LA-VALLEE, FRANCE,183%,5340,1884,1410,5245
5,TIVOLI GARDENS, COPENHAGEN, DENMARK,61%,3864,2400,1628,4581
6,PORTAVENTURA WORLD, SALOU, SPAIN,56%,3750,2400,700,3750
7,LISEBERG, GOTHENBURG, SWEDEN,73%,2500,1447,0,2950
8,GARDALAND, CASTELNUOVO DEL GARDA, ITALY,34%,2950,2200,1350,2920
9,LEGOLAND WINDSOR, WINDSOR, U.K.,60%,2400,1500,450,2430
10,PARC ASTERIX, PLAILLY, FRANCE,102%,2632,1300,1163,2326
11,PUY DU FOU, LES EPESSES, FRANCE,45%,2342,1616,923,2308
12,PARQUE WARNER, MADRID, SPAIN,43%,1860,1300,450,2232
13,ALTON TOWERS, STAFFORDSHIRE, U.K.,28%,2300,1800,670,2130
14,PHANTASIALAND, BRÜHL, GERMANY,78%,2100,1180,1000,2050
15,LEGOLAND BILLUND, BILLUND, DENMARK,164%,2242,850,700,1950
16,THORPE PARK, CHERTSEY, U.K.,-6%,1600,1700,600,1900
17,FUTUROSCOPE, JAUNAY-CLAN, FRANCE,75%,1920,1100,900,1900
18,LEGOLAND DEUTSCHLAND, GÜNZBURG, GERMANY,89%,1700,900,750,1700
19,HEIDE PARK, SOLTAU, GERMANY,23%,1600,1300,950,1700
20,CHESSINGTON WORLD OF ADVENTURES, CHESSINGTON, U.K.,3%,1500,1450,510,1690&quot;

top20_tp_emea = read.table(text = data_text_tp_emea, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_tp_emea) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-amusementtheme-parks-europe-middle-east-africa-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 amusement/theme parks Europe Middle
East Africa in 2019 to 2022</h4>
<pre class="r"><code>top20_tp_emea_clean_df =
  top20_tp_emea |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Amusement/Theme Park&quot;,
    Region = &quot;EMEA&quot;,
    Country_State = Country,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-water-parks-data-of-north-america-2019-2022"
class="section level4">
<h4>Import water parks data of North America 2019-2022</h4>
<pre class="r"><code>data_text_wp_na = &quot;1,DISNEY&#39;S TYPHOON LAGOON WATER PARK AT WALT DISNEY WORLD RESORT, ORLANDO, FL, U.S., 0%, 1915, 0, 0, 2248
2,DISNEY&#39;S BLIZZARD BEACH WATER PARK AT WALT DISNEY WORLD RESORT, ORLANDO, FL, U.S., -92%, 101, 1201, 316, 1983
3,UNIVERSAL&#39;S VOLCANO BAY, ORLANDO, FL, U.S., 9%, 1850, 1691, 551, 1811
4,AQUATICA, ORLANDO, FL, U.S., 35%, 1548, 1147, 528, 1533
5,SCHLITTERBAHN, NEW BRAUNFELS, TX, U.S., 7%, 946, 888, 451, 996
6,WATER COUNTRY USA, WILLIAMSBURG, VA, U.S., 1%, 707, 700, 0, 736
7,ADVENTURE ISLAND, TAMPA, FL, U.S., 7%, 636, 593, 125, 656
8,AQUATICA SAN ANTONIO, SAN ANTONIO, TX, U.S., 8%, 631, 586, 263, 651
9,SCHLITTERBAHN, GALVESTON, TX, U.S., 34%, 539, 402, 337, 567
10,SPLISH SPLASH, CALVERTON, NY, U.S., 0, 0, 0, 0, 542
11,SIX FLAGS HURRICANE HARBOR, ARLINGTON, TX, U.S., 3%, 388, 377, 235, 538
12,SIX FLAGS WHITE WATER ATLANTA, MARIETTA, GA, U.S., -5%, 350, 368, 238, 526
13,SIX FLAGS HURRICANE HARBOR, JACKSON, NJ, U.S., -5%, 426, 448, 85, 482
14,TYPHOON TEXAS, KATY, TX, U.S., 7%, 364, 340, 203, 478
15,SIX FLAGS HURRICANE HARBOR SPLASHTOWN, SPRING, TX, U.S., 3%, 343, 333, 0, 475
16,ZOOMBEZI BAY, POWELL, OH, U.S., 7%, 399, 373, 176, 466
17,SIX FLAGS HURRICANE HARBOR PHOENIX, GLENDALE, AZ, U.S., 3%, 318, 309, 0, 441
18,CAMELBEACH, TANNERSVILLE, PA, U.S., 66%, 373, 225, 151, 439
19,DOLLYWOOD&#39;S SPLASH COUNTRY, PIGEON FORGE, TN, U.S., 31%, 368, 281, 188, 433
20,CEDAR POINT SHORES, SANDUSKY, OH, U.S., 1%, 405, 402, 0, 424&quot;

top20_wp_na = read.table(text = data_text_wp_na, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;)
colnames(top20_wp_na) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;State&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-water-parks-north-america-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 water parks North America in 2019
to 2022</h4>
<pre class="r"><code>top20_wp_na_clean_df =
  top20_wp_na |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Water Park&quot;,
    Region = &quot;North America&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-water-parks-data-of-latin-america-2019-2022"
class="section level4">
<h4>Import water parks data of Latin America 2019-2022</h4>
<pre class="r"><code>data_text_wp_la = &quot;1, THERMAS DOS LARANJAIS, OLIMPIA, BRAZIL, 47%, 1729, 1179, 922, 1845
2, BAHAMAS AQUAVENTURE WATER PARK, PARADISE ISLAND (NASSAU NEW PROVIDENCE), BAHAMAS, 38%, 1751, 1269, 494, 1813
3, HOT PARK RIO QUENTE, RIO QUENTE, BRAZIL, 53%, 1430, 933, 734, 1469
4, PARQUE ACUATICO XOCOMIL, SAN MARTÍN ZAPOTITLÁN, GUATEMALA, 33%, 833, 626, 121, 894
5, BEACH PARK, AQUIRAZ, BRAZIL, 56%, 782, 500, 312, 890
6, PISCILAGO, GIRARDOT (BOGOTÁ), COLOMBIA, 34%, 816, 609, 307, 876
7, MAGIC CITY WATER PARK, SUZANO, BRAZIL, 32%, 616, 467, 355, 681
8, THERMAS WATER PARK, SÃO PEDRO, BRAZIL, 67%, 753, 452, 315, 641
9, HOT BEACH, OLYMPIA, BRAZIL, 54%, 914, 594, 243, 608
10, PARQUE ACUATICO EL ROLLO, MORELOS, MEXICO, 33%, 489, 368, 210, 525&quot;

top10_wp_la = read.table(text = data_text_wp_la, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top10_wp_la) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-10-water-parks-latin-america-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 10 water parks Latin America in 2019
to 2022</h4>
<pre class="r"><code>top10_wp_la_clean_df =
  top10_wp_la |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Water Park&quot;,
    Region = &quot;Latin America&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-water-parks-data-of-asia-pacific-2019-2022"
class="section level4">
<h4>Import water parks data of Asia Pacific 2019-2022</h4>
<pre class="r"><code>data_text_wp_apac = &quot;1, CHIMELONG WATER PARK, GUANGZHOU, CHINA, -27%, 1620, 2230, 1512, 3014
2, WUHU FANTAWILD WATER PARK, WUHU, CHINA, 115%, 928, 431, 770, 1348
3, CARIBBEAN BAY, SEOUL, SOUTH KOREA, 348%, 995, 222, 168, 1333
4, PLAYA MAYA WATER PARK, WUHAN, CHINA, -23%, 560, 730, 930, 1210
5, AQUAVENTURE ATLANTIS, SANYA, CHINA, -48%, 630, 1200, 1200, 1200
6, SUNWAY LAGOON, KUALA LUMPUR, MALAYSIA, 58%, 950, 600, 600, 1200
7, WET &#39;N&#39; WILD GOLD COAST, GOLD COAST, AUSTRALIA, 6%, 1030, 970, 952, 1120
8, OCEAN WORLD, HONGCHEON, SOUTH KOREA, 552%, 750, 115, 180, 1071
9, POSEIDON BEACH WATER WORLD, HARBIN, CHINA, 7%, 625, 582, 300, 917
10, SUNWAY LOST WORLD OF TAMBUN, PERAK, MALAYSIA, 33%, 800, 600, 600, 1000
11, PLAYA MAYA WATER PARK, SHANGHAI, CHINA, -73%, 290, 1080, 860, 970
12, ATLANTIS WATER ADVENTURE, JAKARTA, INDONESIA, 777%, 263, 30, 220, 910
13, ZHENGZHOU FANTAWILD WATER PARK, ZHENGZHOU, CHINA, 9%, 484, 443, 622, 905
14, SUMMERLAND, TOKYO, JAPAN, 6%, 690, 650, 454, 868
15, XIAMEN FANTAWILD WATERPARK, XIAMEN, CHINA, 23%, 674, 548, 442, 832
16, THE JUNGLE WATER ADVENTURE, BOGOR, INDONESIA, 117%, 582, 268, 200, 785
17, PLAYA MAYA WATER PARK, TIANJIN, CHINA, -14%, 630, 730, 550, 750
18, WOONGJIN PLAYDOCI WATERDOCI, BUCHEON, SOUTH KOREA, 252%, 327, 93, 146, 750
19, LOTTE WATER PARK, GIMHAE, SOUTH KOREA, 603%, 548, 78, 133, 740
20, ADVENTURE COVE WATER PARK, Sentosa, SINGAPORE, 9%, 360, 330, 300, 710&quot;

top20_wp_apac = read.table(text = data_text_wp_apac, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_wp_apac) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-water-parks-asia-pacific-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 water parks Asia Pacific in 2019 to
2022</h4>
<pre class="r"><code>top20_wp_apac_clean_df =
  top20_wp_apac |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Water Park&quot;,
    Region = &quot;Asia Pacific&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-the-water-parks-data-of-europe-middle-east-africa"
class="section level4">
<h4>Import the water parks data of Europe Middle East Africa</h4>
<pre class="r"><code>data_text_wp_emea = &quot;1, THERME ERDING, ERDING, GERMANY, 143%, 1700, 700, 750, 1850
2, AQUAVENTURE WATER PARK, DUBAI, U.A.E., 88%, 1500, 800, 600, 1322
3, AQUAPALACE, PRAGUE, CZECH REPUBLIC, 107%, 1200, 580, 537, 1300
4, TROPICAL ISLANDS, KRAUSNICK, GERMANY, 130%, 1150, 500, 493, 1233
5, SIAM PARK, SANTA CRUZ DE TENERIFE, SPAIN, 125%, 1150, 511, 97, 1200
6, AQUALAND MORAVIA, PASOHLÁVKY, CZECH REPUBLIC, 88%, 727, 386, 368, 806
7, TIKI POOL, DUINRELL, NETHERLANDS, 88%, 750, 400, 390, 800
8, NETTEBAD, OSNABRÜCK, GERMANY, 87%, 650, 347, 311, 756
9, WILD WADI, DUBAI, U.A.E., 60%, 750, 470, 350, 740
10, LALANDIA, BILLUND, DENMARK, 67%, 750, 450, 240, 682&quot;
top10_wp_emea = read.table(text = data_text_wp_emea, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;)
colnames(top10_wp_emea) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-10-water-parks-europe-middle-east-africa-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 10 water parks Europe Middle East
Africa in 2019 to 2022</h4>
<pre class="r"><code>top10_wp_emea_clean_df =
  top10_wp_emea |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Water Park&quot;,
    Region = &quot;EMEA&quot;,
    Country_State = Country,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-museums-data-of-worldwide-2019-2022"
class="section level4">
<h4>Import museums data of Worldwide 2019-2022</h4>
<pre class="r"><code>data_text_mu_ww = &quot;1, LOUVRE, PARIS, FRANCE, 173%, 7726, 2825, 2700, 9600
2, NATIONAL MUSEUM OF CHINA, BEIJING, CHINA, -31%, 1631, 2378, 1600, 7390
3, VATICAN MUSEUMS, VATICAN, VATICAN CITY, 215%, 5081, 1613, 1300, 6883
4, THE METROPOLITAN MUSEUM OF ART, NEW YORK, U.S., 64%, 3209, 1958, 1125, 6770
5, BRITISH MUSEUM, LONDON, U.K., 209%, 4097, 1327, 1275, 6208
6, TATE MODERN, LONDON, U.K., 236%, 3883, 1156, 1433, 6098
7, NATIONAL GALLERY, LONDON, U.K., 285%, 2727, 709, 1197, 6011
8, NATURAL HISTORY MUSEUM, LONDON, U.K., 198%, 4655, 1564, 1197, 5424
9, AMERICAN MUSEUM OF NATURAL HISTORY, NEW YORK, U.S., 0, 0, 0, 0, 5000
10, STATE HERMITAGE, ST. PETERSBURG, RUSSIA, 71%, 2813, 1649, 969, 4957
11, SHANGHAI SCIENCE AND TECHNOLOGY MUSEUM, SHANGHAI, CHINA, -79%, 494, 2368, 1351, 4824
12, REINA SOFÍA, MADRID, SPAIN, 84%, 3063, 1643, 1248, 4426
13, NATIONAL MUSEUM OF NATURAL HISTORY, WASHINGTON, U.S., 297%, 3900, 982, 573, 4200
14, NANJING MUSEUM, NANJING, CHINA, -21%, 1610, 2034, 1515, 4169
15, ZHEJIANG MUSEUM, HANGZHOU, CHINA, -6%, 874, 929, 1108, 4150
16, NATIONAL GALLERY OF ART, WASHINGTON, U.S., 91%, 3256, 1705, 730, 4074
17, VICTORIA &amp; ALBERT MUSEUM, LONDON, U.K., 176%, 2370, 858, 872, 3921
18, CHINA SCIENCE TECHNOLOGY MUSEUM, BEIJING, CHINA, -39%, 1431, 2360, 690, 3891
19, NATIONAL PALACE MUSEUM, TAIPEI, TAIWAN, 149%, 1040, 417, 643, 3832
20, MUSÉE D&#39;ORSAY, PARIS, FRANCE, 213%, 3270, 1044, 867, 3652&quot;

top20_mu_ww = read.table(text = data_text_mu_ww, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_mu_ww) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-museums-worldwide-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 museums Worldwide in 2019 to
2022</h4>
<pre class="r"><code>top20_mu_ww_clean_df =
  top20_mu_ww |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Museum&quot;,
    Region = &quot;Worldwide&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-museums-data-of-north-america-2019-2022"
class="section level4">
<h4>Import museums data of North America 2019-2022</h4>
<pre class="r"><code>data_text_mu_na = &quot;1, THE METROPOLITAN MUSEUM OF ART, NEW YORK, NY, U.S., 64%, 3209, 1958, 1125, 6770
2, AMERICAN MUSEUM OF NATURAL HISTORY, NEW YORK, NY, U.S., 0, 0, 0, 0, 5000
3, NATIONAL MUSEUM OF NATURAL HISTORY, WASHINGTON, DC, U.S., 297%, 3900, 982, 573, 4200
4, NATIONAL GALLERY OF ART, WASHINGTON, DC, U.S., 91%, 3256, 1705, 730, 4074
5, NATIONAL AIR AND SPACE MUSEUM, WASHINGTON, DC, U.S., 2%, 419, 411, 267, 3200
6, NATIONAL MUSEUM OF AMERICAN HISTORY, WASHINGTON, DC, U.S., 216%, 1800, 570, 311, 2800
7, CALIFORNIA SCIENCE CENTER, LOS ANGELES, CA, U.S., 133%, 1694, 726, 271, 2200
8, NATIONAL MUSEUM OF AFRICAN AMERICAN HISTORY AND CULTURE, WASHINGTON, DC, U.S., 178%, 1093, 393, 368, 2000
9, SMITHSONIAN AMERICAN ART MUSEUM (WITH THE RENWICK GALLERY), WASHINGTON, DC, U.S., 162%, 1100, 420, 387, 2000
10, THE MUSEUM OF MODERN ART, NEW YORK, NY, U.S., 89%, 2190, 1161, 706, 1992
11, HOUSTON MUSEUM OF NATURAL SCIENCE, HOUSTON, TX, U.S., 40%, 1520, 1086, 0, 1974
12, NATIONAL PORTRAIT GALLERY, WASHINGTON, DC, U.S., 189%, 954, 330, 321, 1700
13, THE ART INSTITUTE OF CHICAGO, CHICAGO, IL, U.S., 38%, 1037, 700, 375, 1666
14, U.S. HOLOCAUST MEMORIAL MUSEUM, WASHINGTON, DC, U.S., 164%, 1184, 448, 0, 1600
15, FIELD MUSEUM OF NATURAL HISTORY, CHICAGO, IL, U.S., 68%, 1018, 605, 316, 1494
16, DENVER MUSEUM OF NATURE &amp; SCIENCE, DENVER, CO, U.S., 20%, 1151, 959, 991, 1487
17, MUSEUM OF SCIENCE, BOSTON, MA, U.S., 93%, 1123, 583, 345, 1458
18, THE J. PAUL GETTY CENTER, LOS ANGELES, CA, U.S., 80%, 909, 504, 267, 1439
19, MUSEUM OF SCIENCE AND INDUSTRY, CHICAGO, IL, U.S., 45%, 1134, 780, 291, 1388
20, CALIFORNIA ACADEMY OF SCIENCES, SAN FRANCISCO, CA, U.S., 50%, 966, 646, 240, 1321&quot;

top20_mu_na = read.table(text = data_text_mu_na, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_mu_na) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;State&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-museums-north-america-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 museums North America in 2019 to
2022</h4>
<pre class="r"><code>top20_mu_na_clean_df =
  top20_mu_na |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Museum&quot;,
    Region = &quot;North America&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-museums-data-of-asia-pacific-2019-2022"
class="section level4">
<h4>Import museums data of Asia Pacific 2019-2022</h4>
<pre class="r"><code>data_text_mu_apac = &quot;1, NATIONAL MUSEUM OF CHINA, BEIJING, CHINA, -31%, 1631, 2378, 1600, 7390
2, SHANGHAI SCIENCE &amp; TECHNOLOGY MUSEUM, SHANGHAI, CHINA, -79%, 494, 2368, 1351, 4824
3, NANJING MUSEUM, NANJING, CHINA, -21%, 1610, 2034, 1515, 4169
4, ZHEJIANG MUSEUM, HANGZHOU, CHINA, -6%, 874, 929, 1108, 4150
5, CHINA SCIENCE TECHNOLOGY MUSEUM, BEIJING, CHINA, -39%, 1431, 2360, 690, 3891
6, NATIONAL PALACE MUSEUM, TAIPEI, TAIWAN, 149%, 1040, 417, 643, 3832
7, XIAN MUSEUM, XIAN, CHINA, 27%, 401, 315, 348, 3420
8, NATIONAL MUSEUM OF KOREA, SEOUL, SOUTH KOREA, 170%, 3411, 1263, 774, 3354
9, TIANJIN NATURAL HISTORY MUSEUM, TIANJIN, CHINA, -17%, 1321, 1600, 550, 3150
10, HUNAN MUSEUM, CHANGSHA, CHINA, -14%, 1221, 1421, 1130, 3140
11, NATIONAL TAIWAN SCIENCE EDUCATION CENTER, TAIPEI, TAIWAN, 62%, 1879, 1158, 1082, 3000
12, SHANXI HISTORY MUSEUM, XIAN, CHINA, -54%, 690, 1510, 1000, 2900
13, TOKYO METROPOLITAN ART MUSEUM, TOKYO, JAPAN, 44%, 1510, 1049, 510, 2874
14, NATIONAL MUSEUM OF NATURAL SCIENCE, TAICHUNG, TAIWAN, 47%, 2300, 1566, 2263, 2650
15, SHANGHAI NATURAL HISTORY MUSEUM, SHANGHAI, CHINA, -75%, 532, 2166, 1040, 2549
16, NATIONAL MUSEUM OF NATURE AND SCIENCE, TOKYO, JAPAN, 69%, 1350, 800, 580, 2460
17, ZHEJIANG MUSEUM OF NATURAL HISTORY, HANGZHOU, CHINA, 0%, 738, 740, 600, 2443
18, NATIONAL GALLERY OF VICTORIA, MELBOURNE, AUSTRALIA, 97%, 1580, 802, 637, 2433
19, TOKYO NATIONAL MUSEUM, TOKYO, JAPAN, 127%, 1372, 605, 725, 2431
20, HUBEI PROVINCIAL MUSEUM, WUHAN, CHINA, 37%, 1000, 730, 446, 2400&quot;

top20_mu_apac = read.table(text = data_text_mu_apac, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_mu_apac) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-museums-asia-pacific-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 museums Asia Pacific in 2019 to
2022</h4>
<pre class="r"><code>top20_mu_apac_clean_df =
  top20_mu_apac |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Museum&quot;,
    Region = &quot;Asia Pacific&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
<div id="import-museums-data-of-europe-middle-east-africa-2019-2022"
class="section level4">
<h4>Import museums data of Europe Middle East Africa 2019-2022</h4>
<pre class="r"><code>data_text_mu_emea = &quot;1, LOUVRE, PARIS, FRANCE, 173%, 7726, 2825, 2700, 9600
2, VATICAN MUSEUMS, VATICAN, VATICAN CITY, 215%, 5081, 1613, 1300, 6883
3, BRITISH MUSEUM, LONDON, U.K., 209%, 4097, 1327, 1275, 6208
4, TATE MODERN, LONDON, U.K., 236%, 3883, 1156, 1433, 6098
5, NATIONAL GALLERY, LONDON, U.K., 285%, 2727, 709, 1197, 6011
6, NATURAL HISTORY MUSEUM, LONDON, U.K., 198%, 4655, 1564, 1197, 5424
7, STATE HERMITAGE, ST PETERSBURG, RUSSIA, 71%, 2813, 1649, 969, 4957
8, REINA SOFÍA, MADRID, SPAIN, 86%, 3063, 1643, 1248, 4426
9, VICTORIA &amp; ALBERT MUSEUM, LONDON, U.K., 176%, 2370, 858, 872, 3921
10, MUSÉE D&#39;ORSAY, PARIS, FRANCE, 213%, 3270, 1044, 867, 3652
11, CENTRE POMPIDOU, PARIS, FRANCE, 101%, 3010, 1501, 913, 3270
12, SCIENCE MUSEUM (SOUTH KENSINGTON), LONDON, U.K., 262%, 2335, 646, 862, 3254
13, MUSEO NACIONAL DEL PRADO, MADRID, SPAIN, 118%, 2457, 1127, 852, 3203
14, STATE TRETYAKOV GALLERY, MOSCOW, RUSSIA, 21%, 1910, 1581, 894, 2836
15, RIJKSMUSEUM, AMSTERDAM, NETHERLANDS, 183%, 1766, 625, 675, 2700
16, CITE DES SCIENCES ET DE L&#39;INDUSTRIE, PARIS, FRANCE, 114%, 2101, 984, 793, 2370
17, GALLERIA DEGLI UFFIZI, FLORENCE, ITALY, 129%, 2223, 970, 659, 2362
18, AUSCHWITZ-BIRKENAU MUSEUM, OŚWIĘCIM, POLAND, 110%, 1184, 563, 502, 2300
19, NATIONAL MUSEUM OF SCOTLAND, EDINBURGH, U.K., 199%, 1974, 661, 444, 2210
20, VAN GOGH MUSEUM, AMSTERDAM, NETHERLANDS, 267%, 1346, 366, 517, 2100&quot;

top20_mu_emea = read.table(text = data_text_mu_emea, sep = &quot;,&quot;, header = FALSE, quote = &quot;&quot;, na.strings = &quot;-&quot;)
colnames(top20_mu_emea) = c(&quot;id&quot;,&quot;Park_Name&quot;, &quot;City&quot;, &quot;Country&quot;, &quot;%Change&quot;, &quot;2022&quot;, &quot;2021&quot;, &quot;2020&quot;, &quot;2019&quot;)</code></pre>
</div>
<div
id="clean-the-dataset-for-the-top-20-museums-europe-middle-east-africa-in-2019-to-2022"
class="section level4">
<h4>Clean the dataset for the top 20 museums Europe Middle East Africa
in 2019 to 2022</h4>
<pre class="r"><code>top20_mu_emea_clean_df =
  top20_mu_emea |&gt;
  pivot_longer(
    (&quot;2019&quot;):(&quot;2022&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Attendance&quot;
  ) |&gt;
  mutate(
    Type = &quot;Museum&quot;,
    Region = &quot;Europe Middle East Africa&quot;,
    Attendance = Attendance * 10e3
  ) |&gt;
  select(
    Park_Name, City, Country, Year, Attendance, Type, Region
  )</code></pre>
</div>
</div>
<div id="combine-all-dataset" class="section level3">
<h3>Combine all dataset</h3>
<pre class="r"><code>combine_df = 
  bind_rows(top25_tp_ww_clean_df, top20_tp_na_clean_df, top10_tp_la_clean_df, top20_tp_apac_clean_df, top20_tp_emea_clean_df, top20_wp_na_clean_df, top10_wp_la_clean_df, top20_wp_apac_clean_df, top10_wp_emea_clean_df, top20_mu_ww_clean_df, top20_mu_na_clean_df, top20_mu_apac_clean_df, top20_mu_emea_clean_df)</code></pre>
</div>
<div id="export-the-final-dataset" class="section level3">
<h3>Export the final dataset</h3>
<pre class="r"><code>write.csv(combine_df, &quot;ultimate data.csv&quot;, row.names = FALSE)</code></pre>
</div>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory analysis</h2>
<p>After tidying our data set, an exploratory analysis is conducted to
look for possible predictors for the <code>Attendance</code>
outcome.</p>
<div id="descriptive-analysis-for-all-data" class="section level3">
<h3>Descriptive Analysis for All Data</h3>
<div id="total-attendance-by-type-from-2019-to-2022"
class="section level4">
<h4>Total Attendance by Type from 2019 to 2022</h4>
<p>A brief summary of attendance based on the <code>Type</code> variable
is provided below:</p>
<table>
<caption>Summary of Attendance for Three Types of Facilities From 2019
to 2022</caption>
<thead>
<tr class="header">
<th align="left">Year</th>
<th align="right">Amusement/Theme Park</th>
<th align="right">Museum</th>
<th align="right">Water Park</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2019</td>
<td align="right">37996.4</td>
<td align="right">20100.8</td>
<td align="right">5898.9</td>
</tr>
<tr class="even">
<td align="left">2020</td>
<td align="right">13031.1</td>
<td align="right">4664.5</td>
<td align="right">2313.5</td>
</tr>
<tr class="odd">
<td align="left">2021</td>
<td align="right">22463.7</td>
<td align="right">6459.0</td>
<td align="right">3473.5</td>
</tr>
<tr class="even">
<td align="left">2022</td>
<td align="right">21280.8</td>
<td align="right">11603.3</td>
<td align="right">4678.3</td>
</tr>
</tbody>
</table>
<p>From this table, some observed patterns are:</p>
<ul>
<li>A common decreasing trend of attendance from 2019 and 2020</li>
<li>A common increasing trend of attendance from 2020 and 2022</li>
</ul>
<p>The distribution of data by year is further visualized into the box
plots below:</p>
<pre class="r"><code>theme_park |&gt; 
  group_by(Year) |&gt; 
  plot_ly(y = ~Attendance, color = ~Year, type = &quot;box&quot;, colors = &quot;viridis&quot;) |&gt; 
  layout(annotations = 
 list(x = 1, y =1, text = &quot;Plot 1: Distribution of Attendance by Year&quot;, 
      showarrow = F, xref=&#39;paper&#39;, yref=&#39;paper&#39;, 
      xanchor=&#39;right&#39;, yanchor=&#39;auto&#39;, xshift=0, yshift=0,
      font=list(size=15))
 )</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-04e8f38dc386c5fd3987" style="width:90%;height:576px;"></div>
<script type="application/json" data-for="htmlwidget-04e8f38dc386c5fd3987">{"x":{"visdat":{"1d1847ed4dda":["function () ","plotlyVisDat"]},"cur_data":"1d1847ed4dda","attrs":{"1d1847ed4dda":{"y":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"annotations":[{"x":1,"y":1,"text":"Plot 1: Distribution of Attendance by Year","showarrow":false,"xref":"paper","yref":"paper","xanchor":"right","yanchor":"auto","xshift":0,"yshift":0,"font":{"size":15}}],"yaxis":{"domain":[0,1],"automargin":true,"title":"Attendance"},"xaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"fillcolor":"rgba(68,1,84,0.5)","y":[209630000,186660000,138880000,124440000,114830000,109220000,103750000,98610000,91470000,46400000,42380000,41800000,39500000,37310000,36100000,35210000,34850000,34510000,33840000,31690000,28030000,22410000,19600000,13300000,13060000,11730000,11510000,11000000,10430000,9680000,179100000,146500000,145000000,117360000,112100000,66060000,59530000,59500000,57000000,56950000,51600000,49050000,45000000,44340000,39900000,39800000,38400000,35800000,35750000,33900000,97450000,57500000,52600000,52450000,45810000,37500000,29500000,29200000,24300000,23260000,23080000,22320000,21300000,20500000,19500000,19000000,19000000,17000000,17000000,16900000,22480000,19830000,18110000,15330000,9960000,7360000,6560000,6510000,5670000,5420000,5380000,5260000,4820000,4780000,4750000,4660000,4410000,4390000,4330000,4240000,18450000,18130000,14690000,8940000,8900000,8760000,6810000,6410000,6080000,5250000,30140000,13480000,13330000,12100000,12000000,12000000,11200000,10710000,9170000,10000000,9700000,9100000,9050000,8680000,8320000,7850000,7500000,7500000,7400000,7100000,18500000,13220000,13000000,12330000,12000000,8060000,8000000,7560000,7400000,6820000,67700000,50000000,42000000,40740000,32000000,28000000,22000000,20000000,20000000,19920000,19740000,17000000,16660000,16000000,14940000,14870000,14580000,14390000,13880000,13210000,73900000,48240000,41690000,41500000,38910000,38320000,34200000,33540000,31500000,31400000,30000000,29000000,28740000,26500000,25490000,24600000,24430000,24330000,24310000,24000000,96000000,68830000,62080000,60980000,60110000,54240000,49570000,44260000,39210000,36520000,32700000,32540000,32030000,28360000,27000000,23700000,23620000,23000000,22100000,21000000],"type":"box","name":"2019","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"fillcolor":"rgba(49,104,142,0.5)","y":[69410000,36740000,41660000,40440000,36750000,40960000,40050000,19190000,12990000,15980000,8110000,12880000,0,11390000,10200000,6860000,16260000,5980000,17170000,0,7010000,12520000,7360000,2680000,0,0,3440000,4300000,3210000,2630000,41600000,34000000,49010000,47970000,55000000,27600000,15600000,24000000,22000000,17000000,39500000,26810000,10980000,23750000,18900000,31200000,34210000,26200000,22570000,27300000,26200000,25000000,29000000,14100000,16280000,7000000,0,13500000,4500000,11630000,9230000,4500000,6700000,10000000,7000000,6000000,9000000,7500000,9500000,5100000,0,3160000,5510000,5280000,4510000,0,1250000,2630000,3370000,0,2350000,2380000,850000,2030000,0,1760000,0,1510000,1880000,0,9220000,4940000,7340000,1210000,3120000,3070000,3550000,3150000,2430000,2100000,15120000,7700000,1680000,9300000,12000000,6000000,9520000,1800000,3000000,6000000,8600000,2200000,6220000,4540000,4420000,2000000,5500000,1460000,1330000,3000000,7500000,6000000,5370000,4930000,970000,3680000,3900000,3110000,3500000,2400000,11250000,0,5730000,7300000,2670000,3110000,2710000,3680000,3870000,7060000,0,3210000,3750000,0,3160000,9910000,3450000,2670000,2910000,2400000,16000000,13510000,15150000,11080000,6900000,6430000,3480000,7740000,5500000,11300000,10820000,10000000,5100000,22630000,10400000,5800000,6000000,6370000,7250000,4460000,27000000,13000000,12750000,14330000,11970000,11970000,9690000,12480000,8720000,8670000,9130000,8620000,8520000,8940000,6750000,7930000,6590000,5020000,4440000,5170000],"type":"box","name":"2020","marker":{"color":"rgba(49,104,142,1)","line":{"color":"rgba(49,104,142,1)"}},"line":{"color":"rgba(49,104,142,1)"},"xaxis":"x","yaxis":"y","frame":null},{"fillcolor":"rgba(53,183,121,0.5)","y":[126910000,85730000,71940000,77520000,85890000,89870000,90770000,49770000,55050000,30510000,36810000,32100000,5870000,28000000,33270000,30470000,31810000,29130000,30120000,26750000,11250000,18950000,11040000,4020000,0,0,6310000,6150000,4820000,3950000,63000000,58000000,55000000,74520000,84800000,37100000,24600000,36000000,14000000,28000000,49300000,38900000,12000000,25000000,24000000,33100000,27520000,29400000,23080000,33000000,35000000,30000000,33000000,18840000,24000000,24000000,14470000,22000000,15000000,13000000,16160000,13000000,18000000,11800000,8500000,17000000,11000000,9000000,13000000,14500000,0,12010000,16910000,11470000,8880000,7000000,5930000,5860000,4020000,0,3770000,3680000,4480000,3400000,3330000,3730000,3090000,2250000,2810000,4020000,11790000,12690000,9330000,6260000,5000000,6090000,4670000,4520000,5940000,3680000,22300000,4310000,2220000,7300000,12000000,6000000,9700000,1150000,5820000,6000000,10800000,300000,4430000,6500000,5480000,2680000,7300000,930000,780000,3300000,7000000,8000000,5800000,5000000,5110000,3860000,4000000,3470000,4700000,4500000,19580000,0,9820000,17050000,4110000,5700000,7260000,3930000,4200000,11610000,10860000,3300000,7000000,4480000,6050000,9590000,5830000,5040000,7800000,6460000,23780000,23680000,20340000,9290000,23600000,4170000,3150000,12630000,16000000,14210000,11580000,15100000,10490000,15660000,21660000,8000000,7400000,8020000,6050000,7300000,28250000,16130000,13270000,11560000,7090000,15640000,16490000,16430000,8580000,10440000,15010000,6460000,11270000,15810000,6250000,9840000,9700000,5630000,6610000,3660000],"type":"box","name":"2021","marker":{"color":"rgba(53,183,121,1)","line":{"color":"rgba(53,183,121,1)"}},"line":{"color":"rgba(53,183,121,1)"},"xaxis":"x","yaxis":"y","frame":null},{"fillcolor":"rgba(253,231,37,0.5)","y":[171330000,168810000,90270000,100000000,109000000,107500000,110250000,90000000,84000000,44540000,38990000,40510000,37680000,35070000,34440000,29930000,33400000,21530000,31930000,25350000,17270000,23270000,13990000,8000000,0,0,7520000,8500000,6260000,5140000,99300000,54000000,54300000,53400000,38640000,37500000,25000000,29500000,24000000,26320000,23420000,18600000,23000000,21000000,22420000,16000000,19200000,17000000,16000000,15000000,19150000,1010000,18500000,15480000,9460000,7070000,6360000,6310000,5390000,0,3880000,3500000,4260000,3640000,3430000,3990000,3180000,3730000,3680000,4050000,17290000,17510000,14300000,8330000,7820000,8160000,6160000,7530000,9140000,4890000,16200000,9280000,9950000,5600000,6300000,9500000,10300000,7500000,6250000,8000000,2900000,2630000,4840000,6900000,6740000,5820000,6300000,3270000,5480000,3600000,17000000,15000000,12000000,11500000,11500000,7270000,7500000,6500000,7500000,7500000,32090000,0,39000000,32560000,4190000,18000000,16940000,10930000,11000000,21900000,15200000,9540000,10370000,11840000,10180000,11510000,11230000,9090000,11340000,9660000,16310000,4940000,16100000,8740000,14310000,10400000,4010000,34110000,13210000,12210000,18790000,6900000,15100000,23000000,5320000,13500000,7380000,15800000,13720000,10000000,77260000,50810000,40970000,38830000,27270000,46550000,28130000,30630000,23700000,32700000,30100000,23350000,24570000,19100000,17660000,21010000,22230000,11840000,19740000,13460000],"type":"box","name":"2022","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li>Overall high attendance in 2019 and low attendance in 2020</li>
<li>Common outliers in the distribution of attendance for each year</li>
</ul>
</div>
<div id="total-attendance-by-region-from-2019-to-2022"
class="section level4">
<h4>Total Attendance by Region from 2019 to 2022</h4>
<p>Next, we specifically look at the trend of <code>Attendance</code>
from 2019 to 2022 based on the <code>Region</code> variable.</p>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-fa5f762da5c7cab3c58b" style="width:90%;height:576px;"></div>
<script type="application/json" data-for="htmlwidget-fa5f762da5c7cab3c58b">{"x":{"visdat":{"1d1865b614fd":["function () ","plotlyVisDat"]},"cur_data":"1d1865b614fd","attrs":{"1d1865b614fd":{"x":{},"y":{},"mode":"point","color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"annotations":[{"x":1,"y":1,"text":"Plot 2: Change in Attendance for Each Region","showarrow":false,"xref":"paper","yref":"paper","xanchor":"right","yanchor":"auto","xshift":0,"yshift":0,"font":{"size":15}}],"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["2019","2020","2021","2022"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"attend_sum"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["2019","2020","2021","2022"],"y":[38392833.333333336,14875166.666666666,19195500,10030250],"mode":"point","type":"scatter","name":"Asia Pacific","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2019","2020","2021","2022"],"y":[25068666.666666668,8770000,13757000,24562333.333333332],"mode":"point","type":"scatter","name":"EMEA","marker":{"color":"rgba(59,82,139,1)","line":{"color":"rgba(59,82,139,1)"}},"textfont":{"color":"rgba(59,82,139,1)"},"error_y":{"color":"rgba(59,82,139,1)"},"error_x":{"color":"rgba(59,82,139,1)"},"line":{"color":"rgba(59,82,139,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2019","2020","2021","2022"],"y":[41892500,10084500,11706000,29995500],"mode":"point","type":"scatter","name":"Europe Middle East Africa","marker":{"color":"rgba(33,144,141,1)","line":{"color":"rgba(33,144,141,1)"}},"textfont":{"color":"rgba(33,144,141,1)"},"error_y":{"color":"rgba(33,144,141,1)"},"error_x":{"color":"rgba(33,144,141,1)"},"line":{"color":"rgba(33,144,141,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2019","2020","2021","2022"],"y":[12658500,4164000,6823000,9554000],"mode":"point","type":"scatter","name":"Latin America","marker":{"color":"rgba(93,200,99,1)","line":{"color":"rgba(93,200,99,1)"}},"textfont":{"color":"rgba(93,200,99,1)"},"error_y":{"color":"rgba(93,200,99,1)"},"error_x":{"color":"rgba(93,200,99,1)"},"line":{"color":"rgba(93,200,99,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["2019","2020","2021","2022"],"y":[37549333.333333336,9338833.333333334,21743333.333333332,30452833.333333332],"mode":"point","type":"scatter","name":"North America","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li>Similar attendance fluctuation for most regions</li>
<li>Only EMEA has an attendance drop from 2021 to 2022</li>
</ul>
</div>
</div>
<div id="descriptive-analysis-for-all-data-worldwide-top-25"
class="section level3">
<h3>Descriptive Analysis For All Data （Worldwide Top 25)</h3>
<div
id="top-25-theme-park-from-worldwides-sum-attendance-by-different-country."
class="section level4">
<h4>Top 25 theme park from worldwide’s sum attendance by different
country.</h4>
<p>Looking at the plot 1, we found that there was too much data for
outliers, so we did another data analysis based on Top 25 theme park,
which is labled as Worldwide on the region variable.</p>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-7418a75e9525691dec70" style="width:90%;height:576px;"></div>
<script type="application/json" data-for="htmlwidget-7418a75e9525691dec70">{"x":{"visdat":{"1d1856c014d7":["function () ","plotlyVisDat"]},"cur_data":"1d1856c014d7","attrs":{"1d1856c014d7":{"x":{},"y":{},"color":{},"colors":"viridis","alpha":0.5,"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"annotations":[{"x":1,"y":1.04,"text":"Plot 3: Distribution of Attendance by different Country in different year","showarrow":false,"xref":"paper","yref":"paper","xanchor":"right","yanchor":"auto","xshift":0,"yshift":0,"font":{"size":15}}],"xaxis":{"domain":[0,1],"automargin":true,"title":"Year"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Attendance"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022],"y":[117360000,47970000,74520000,44000000,112100000,55000000,84800000,53000000,51600000,39500000,49300000,37400000,49050000,26810000,38900000,23000000,73900000,16000000,23780000,16310000,48240000,13510000,23680000,4940000,41690000,15150000,20340000,16100000,41500000,11080000,9290000,8740000,38910000,6900000,23600000,14310000],"type":"bar","name":"CHINA","marker":{"color":"rgba(68,1,84,0.5)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,0.5)"},"error_y":{"color":"rgba(68,1,84,0.5)"},"error_x":{"color":"rgba(68,1,84,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022],"y":[97450000,26200000,35000000,99300000,52450000,14100000,18840000,53400000,96000000,27000000,28250000,77260000,36520000,8670000,10440000,32700000],"type":"bar","name":"FRANCE","marker":{"color":"rgba(72,31,112,0.5)","line":{"color":"rgba(72,31,112,1)"}},"textfont":{"color":"rgba(72,31,112,0.5)"},"error_y":{"color":"rgba(72,31,112,0.5)"},"error_x":{"color":"rgba(72,31,112,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[57500000,25000000,30000000,60000000],"type":"bar","name":"GERMANY","marker":{"color":"rgba(68,58,131,0.5)","line":{"color":"rgba(68,58,131,1)"}},"textfont":{"color":"rgba(68,58,131,0.5)"},"error_y":{"color":"rgba(68,58,131,0.5)"},"error_x":{"color":"rgba(68,58,131,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022],"y":[179100000,41600000,63000000,120000000,146500000,34000000,58000000,101000000,145000000,49010000,55000000,123500000,59500000,24000000,36000000,42000000],"type":"bar","name":"JAPAN","marker":{"color":"rgba(59,82,139,0.5)","line":{"color":"rgba(59,82,139,1)"}},"textfont":{"color":"rgba(59,82,139,0.5)"},"error_y":{"color":"rgba(59,82,139,0.5)"},"error_x":{"color":"rgba(59,82,139,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[52600000,29000000,33000000,54300000],"type":"bar","name":"NETHERLANDS","marker":{"color":"rgba(49,104,142,0.5)","line":{"color":"rgba(49,104,142,1)"}},"textfont":{"color":"rgba(49,104,142,0.5)"},"error_y":{"color":"rgba(49,104,142,0.5)"},"error_x":{"color":"rgba(49,104,142,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[49570000,9690000,16490000,28130000],"type":"bar","name":"RUSSIA","marker":{"color":"rgba(40,124,142,0.5)","line":{"color":"rgba(40,124,142,1)"}},"textfont":{"color":"rgba(40,124,142,0.5)"},"error_y":{"color":"rgba(40,124,142,0.5)"},"error_x":{"color":"rgba(40,124,142,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022],"y":[57000000,22000000,14000000,14000000,56950000,17000000,28000000,34000000],"type":"bar","name":"SAR","marker":{"color":"rgba(33,144,141,0.5)","line":{"color":"rgba(33,144,141,1)"}},"textfont":{"color":"rgba(33,144,141,0.5)"},"error_y":{"color":"rgba(33,144,141,0.5)"},"error_x":{"color":"rgba(33,144,141,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022],"y":[66060000,27600000,37100000,57700000,59530000,15600000,24600000,45200000],"type":"bar","name":"SOUTH KOREA","marker":{"color":"rgba(32,164,134,0.5)","line":{"color":"rgba(32,164,134,1)"}},"textfont":{"color":"rgba(32,164,134,0.5)"},"error_y":{"color":"rgba(32,164,134,0.5)"},"error_x":{"color":"rgba(32,164,134,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[44260000,12480000,16430000,30630000],"type":"bar","name":"SPAIN","marker":{"color":"rgba(53,183,121,0.5)","line":{"color":"rgba(53,183,121,1)"}},"textfont":{"color":"rgba(53,183,121,0.5)"},"error_y":{"color":"rgba(53,183,121,0.5)"},"error_x":{"color":"rgba(53,183,121,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[38320000,6430000,4170000,10400000],"type":"bar","name":"TAIWAN","marker":{"color":"rgba(93,200,99,0.5)","line":{"color":"rgba(93,200,99,1)"}},"textfont":{"color":"rgba(93,200,99,0.5)"},"error_y":{"color":"rgba(93,200,99,0.5)"},"error_x":{"color":"rgba(93,200,99,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022],"y":[62080000,12750000,13270000,40970000,60980000,14330000,11560000,38830000,60110000,11970000,7090000,27270000,54240000,11970000,15640000,46550000,39210000,8720000,8580000,23700000],"type":"bar","name":"U.K.","marker":{"color":"rgba(143,214,68,0.5)","line":{"color":"rgba(143,214,68,1)"}},"textfont":{"color":"rgba(143,214,68,0.5)"},"error_y":{"color":"rgba(143,214,68,0.5)"},"error_x":{"color":"rgba(143,214,68,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022,2019,2020,2021,2022],"y":[209630000,69410000,126910000,171330000,186660000,36740000,85730000,168810000,138880000,41660000,71940000,90270000,124440000,40440000,77520000,100000000,114830000,36750000,85890000,109000000,109220000,40960000,89870000,107500000,103750000,40050000,90770000,110250000,98610000,19190000,49770000,90000000,91470000,12990000,55050000,84000000,67700000,11250000,19580000,32090000,50000000,0,0,0,42000000,5730000,9820000,39000000,40740000,7300000,17050000,32560000],"type":"bar","name":"U.S.","marker":{"color":"rgba(199,224,32,0.5)","line":{"color":"rgba(199,224,32,1)"}},"textfont":{"color":"rgba(199,224,32,0.5)"},"error_y":{"color":"rgba(199,224,32,0.5)"},"error_x":{"color":"rgba(199,224,32,0.5)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[2019,2020,2021,2022],"y":[68830000,13000000,16130000,50810000],"type":"bar","name":"VATICAN CITY","marker":{"color":"rgba(253,231,37,0.5)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,0.5)"},"error_y":{"color":"rgba(253,231,37,0.5)"},"error_x":{"color":"rgba(253,231,37,0.5)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>We use “Worldwide” to rank the top 25 theme parks by total number of
visitors in different countries in different year. According to the
icon, we can get:</p>
<ul>
<li><p>The total number of tourists from U.S. is the largest from 2019
to 2022, followed by China and Japan in third place.</p></li>
<li><p>Russia, Germany and Spain have the lowest total tourist arrivals
in 2019-2022.</p></li>
<li><p>Based on comparisons between different years, we found that the
number of tourists dropped sharply from 2019 to 2020. The number of
tourists from 2020 to 2022 is slowly returning to normal, but it is not
as high as before the epidemic.</p></li>
</ul>
</div>
</div>
<div id="anova-test" class="section level3">
<h3>ANOVA test</h3>
<div id="based-on-type-of-facilities" class="section level4">
<h4>Based on Type of Facilities</h4>
<p>The first ANOVA test focuses on the <code>Type</code> variable in our
data set. The null hypothesis and alternative hypothesis are listed as
follow:</p>
<p><span class="math display">\[H_0: \mu_{\text{Amusement/Theme Park}} =
\mu_{\text{Water Park}} = \mu_{\text{Museum}} ~~ \text{vs} ~~ H_1:
\text{at least two means are not equal}\]</span></p>
<pre class="r"><code>anova_1 = aov(Attendance ~ Type, data = theme_park)

summary(anova_1)</code></pre>
<pre><code>##              Df    Sum Sq   Mean Sq F value Pr(&gt;F)    
## Type          2 1.127e+17 5.635e+16   105.3 &lt;2e-16 ***
## Residuals   737 3.944e+17 5.351e+14                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>With a p-value of less than 2e-16, we would reject the null
hypothesis. We have evidence that at least two of the means are not
equal. Meaning the mean attendance among type groups is different for at
least two groups in the <code>Type</code> variable.</p>
</div>
<div id="based-on-thr-type-of-year" class="section level4">
<h4>Based on thr Type of Year</h4>
<p>The Second ANOVA test focuses on the <code>Year</code> variable in
our data set. The null hypothesis and alternative hypothesis are listed
as follow:</p>
<p><span class="math display">\[H_0: \mu_{\text{2019}} =
\mu_{\text{2020}} = \mu_{\text{2021}}= \mu_{\text{2022}} ~~ \text{vs} ~~
H_1: \text{at least two means are not equal}\]</span></p>
<pre class="r"><code>dat = 
  theme_full |&gt; 
  filter(
    Region != c(&quot;Worldwide&quot;)
    ) |&gt; 
  mutate(
    Year = as.factor(Year)
  ) 

anova2 = aov(Attendance ~ Year , data = dat) 

summary(anova2)</code></pre>
<pre><code>##              Df    Sum Sq   Mean Sq F value Pr(&gt;F)    
## Year          3 5.452e+16 1.817e+16   29.56 &lt;2e-16 ***
## Residuals   736 4.526e+17 6.149e+14                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>With a p-value of less than 2e-16, we would reject the null
hypothesis. We have evidence that at least two of the means are not
equal. Meaning the mean attendance among year groups is different for at
least two groups.</p>
</div>
</div>
</div>
<div id="regression-analysis" class="section level2">
<h2>Regression Analysis</h2>
<div id="linear-regression" class="section level3">
<h3>Linear Regression</h3>
<p>Linear regression is used to model the relationship between
attendance and five independent variables (city, country, year, type,
and region). It assumes that this relationship is linear, meaning
changes in the predictors are associated with a constant change in the
response. We first fit linear regression of each predictors to check if
they are associated with attendance.</p>
<div id="relationship-between-city-and-attendance"
class="section level4">
<h4>Relationship between city and attendance</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-41-1.png" width="90%" /></p>
<p>a few cities are associated with attendance such as ANAHEIM, Beijing,
UNIVERSAL CITY, TOKYO, VATICAN. In general, there is no apparent linear
relationship between city and attendance.</p>
</div>
<div id="relationship-between-country-and-attendance"
class="section level4">
<h4>Relationship between country and attendance</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-43-1.png" width="90%" /></p>
<p>only one country Japan is significantly associated with attendance.
In general, there is no apparent linear relationship between country and
attendance.</p>
</div>
<div id="relationship-between-year-and-attendance"
class="section level4">
<h4>Relationship between year and attendance</h4>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year, data = data_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -22189468 -14873528  -8200722   4982092 184429278 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6104922321 1747418850   3.494 0.000505 ***
## year          -3011254     864862  -3.482 0.000527 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.6e+07 on 738 degrees of freedom
## Multiple R-squared:  0.01616,    Adjusted R-squared:  0.01483 
## F-statistic: 12.12 on 1 and 738 DF,  p-value: 0.0005274</code></pre>
<p>according to the summary of linear regression, <span
class="math inline">\(\widehat{Y}=\widehat{\beta_0}+\widehat{\beta_1}*X\)</span>.
Linear Model: <span
class="math inline">\(\widehat{attendance}=6104922321-3011254*year\)</span>.</p>
<p><img src="final_report_files/figure-html/unnamed-chunk-45-1.png" width="90%" /></p>
<p>Year is significantly associated with attendance, and there is a
linear relationship between year and attendance. Attendance has
experienced a decline from 2019 to 2022.</p>
</div>
<div id="relationship-between-park-type-and-attendance"
class="section level4">
<h4>Relationship between park type and attendance</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-47-1.png" width="90%" /></p>
<p>Park type is significantly associated with attendance.
Amusement/Theme Park has the highest attendance and water park has the
lowest attendance.</p>
</div>
<div id="relationship-between-region-and-attendance"
class="section level4">
<h4>Relationship between region and attendance</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-49-1.png" width="90%" /></p>
<p>Latin America is significantly associated with attendance. Overall,
there is no apparent linear relationship between region and
attendance.</p>
</div>
<div id="fit-a-multiple-linear-regression" class="section level4">
<h4>Fit a Multiple linear regression</h4>
<p>Multiple linear regression allows us to account for the influence of
multiple independent variables on the attendance simultaneously. The
outcomes of the linear regression analysis suggest that the variable
“year” exhibits a linear relationship with attendance. Additionally,
specific categories within the “type” and “region” variables are found
to be significantly associated with attendance. Thus, variables “year”,
“type”, and “region” are used to fit a multiple linear regression.</p>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year + type + region, data = data_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -45964074 -11813664  -4985390   6989976 161399771 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                     4621928259 1470060108   3.144  0.00173 ** 
## year                              -2266156     727662  -3.114  0.00192 ** 
## typeMuseum                       -28938548    2387097 -12.123  &lt; 2e-16 ***
## typeWater Park                   -31241190    1983579 -15.750  &lt; 2e-16 ***
## regionEMEA                       -14707744    2635034  -5.582 3.36e-08 ***
## regionEurope Middle East Africa    9197198    3154499   2.916  0.00366 ** 
## regionLatin America              -19240504    2955262  -6.511 1.39e-10 ***
## regionNorth America                1670022    2040565   0.818  0.41339    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21800000 on 732 degrees of freedom
## Multiple R-squared:  0.3141, Adjusted R-squared:  0.3075 
## F-statistic: 47.88 on 7 and 732 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>only North America within region is not significantly associated with
attendance.</p>
</div>
<div id="stepwise-regression" class="section level4">
<h4>Stepwise regression</h4>
<p>stepwise regression helps streamline the modeling process by
automatically including or excluding variables based on statistical
criteria. We use both backward and forward selection to find the best
fit model.</p>
<pre><code>## Start:  AIC=25016.07
## attendance ~ year + type + region
## 
##          Df  Sum of Sq        RSS   AIC
## &lt;none&gt;                 3.4784e+17 25016
## - year    1 4.6088e+15 3.5245e+17 25024
## - region  4 4.0930e+16 3.8877e+17 25090
## - type    2 1.3329e+17 4.8113e+17 25252</code></pre>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year + type + region, data = data_df)
## 
## Coefficients:
##                     (Intercept)                             year  
##                      4621928259                         -2266156  
##                      typeMuseum                   typeWater Park  
##                       -28938548                        -31241190  
##                      regionEMEA  regionEurope Middle East Africa  
##                       -14707744                          9197198  
##             regionLatin America              regionNorth America  
##                       -19240504                          1670022</code></pre>
<p>The best fit model with lowest AIC is <span
class="math inline">\(\widehat{attendance}=\widehat{\beta_0}+\widehat{\beta_1}*year+\widehat{\beta_2}*type+\widehat{\beta_3}*region\)</span>.</p>
</div>
</div>
<div id="logistic-regression" class="section level3">
<h3>Logistic Regression</h3>
<div id="background" class="section level4">
<h4>Background</h4>
<p>In order to further study the relationship between different stages
of the COVID-19 pandemic and the visitor flow of the theme park, based
on the development process of the pandemic, the years from 2019 to 2022
are divided into two pandemic levels</p>
<ul>
<li><p>Outbreak period: 2019 to 2021</p></li>
<li><p>Control period: 2022</p></li>
</ul>
<p>Then add to our data as <code>pandemic_level</code>.</p>
<p>Furthermore, to classify the pandemic period by park attendance and
other covariates, including Park Type and Region, we established a
logistic regression model with <code>pandemic_level</code> as the
dependent variable.</p>
</div>
<div id="data-preparation" class="section level4">
<h4>Data Preparation</h4>
<pre class="r"><code>#import the data and tidy
set.seed(12138)

park_df =
  read_csv(&quot;ultimate data.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  drop_na()

logistic_df = 
  park_df |&gt;
  mutate(
    type = as.factor(type),
    region = as.factor(region),
    country = as.factor(country),
    pandemic_level = case_when(
      year == 2019 ~ &quot;outbreak&quot;,
      year == 2020 ~ &quot;outbreak&quot;,
      year == 2021 ~ &quot;outbreak&quot;,
      year == 2022 ~ &quot;control&quot;
    ),
    pandemic_level = as.factor(pandemic_level)
  ) </code></pre>
<pre class="r"><code>#attendance relationship
logistic_df |&gt;
  ggplot(aes(park_name, log10(attendance), color = pandemic_level)) +
  geom_point(alpha = .7) +
  facet_grid(. ~ region ) +
  labs(x = &quot;Parks&quot;, y = &quot;Attendance (log10)&quot;,
       caption = &quot;Fig.1 The relationship between park attendance and pandemic level across regions&quot;) +
  theme(axis.text.x = element_blank() )</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-54-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#split data into train and test subset
cv_results = 
  logistic_df |&gt;
  filter(region != &quot;Worldwide&quot;) |&gt;
  mutate(
    pandemic_level = 
      case_match(
        pandemic_level,
        &quot;outbreak&quot; ~ 1,
        &quot;control&quot; ~ 0
      )
  )

cv_df = 
  crossv_mc(
  cv_results,1
)

cv_df =
  cv_df |&gt; 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))</code></pre>
<p>After transforming attendance by log function, the relationship
between the park attendance an the pandemic levels was displayed in
Fig.1.</p>
<p>It can be noticed that different epidemic stages may have different
visitor flow patterns, in other words, the traffic of theme parks from
2019 to 2022 can be classified according to the extent of the epidemic.
This is particularly true in EMEA, the Middle East and Latin
America.</p>
<p>Then the observations in region <em>“Worldwide”</em> were excluded as
redundant data and <code>pandemic_level</code> is converted to a
binomial distribution in order to fit logistic regression models and
predict epidemic levels more easily.</p>
</div>
<div id="logistic-model" class="section level4">
<h4>Logistic model</h4>
<pre class="r"><code>#fit model and selection
log_mod =  
  cv_df |&gt;
  select(train) |&gt;
  unnest(cols = c(train)) |&gt;
  glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = _)

step(log_mod, direction = &quot;forward&quot;) 

best_fit = log_mod</code></pre>
<pre class="r"><code>#model summary
coef(best_fit) |&gt;
  knitr::kable(col.names = c(&quot;Variables&quot; , &quot;Coefficients&quot;),
               caption = &quot;Table.1 The coefficients of model&quot;)</code></pre>
<table>
<caption>Table.1 The coefficients of model</caption>
<thead>
<tr class="header">
<th align="left">Variables</th>
<th align="right">Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2.2365446</td>
</tr>
<tr class="even">
<td align="left">attendance</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">typeMuseum</td>
<td align="right">-0.8417669</td>
</tr>
<tr class="even">
<td align="left">typeWater Park</td>
<td align="right">-0.5368024</td>
</tr>
<tr class="odd">
<td align="left">regionEMEA</td>
<td align="right">-0.7424560</td>
</tr>
<tr class="even">
<td align="left">regionEurope Middle East Africa</td>
<td align="right">-0.0950834</td>
</tr>
<tr class="odd">
<td align="left">regionLatin America</td>
<td align="right">-0.8266498</td>
</tr>
<tr class="even">
<td align="left">regionNorth America</td>
<td align="right">-0.4789397</td>
</tr>
</tbody>
</table>
<pre class="r"><code>best_fit |&gt;
  broom::tidy() |&gt;
  knitr::kable(caption = &quot;Table.2 Summary of the chose model&quot; )</code></pre>
<table>
<caption>Table.2 Summary of the chose model</caption>
<colgroup>
<col width="43%" />
<col width="14%" />
<col width="13%" />
<col width="14%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2.2365446</td>
<td align="right">0.3397519</td>
<td align="right">6.5828760</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">attendance</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
<td align="right">-2.0617899</td>
<td align="right">0.0392277</td>
</tr>
<tr class="odd">
<td align="left">typeMuseum</td>
<td align="right">-0.8417669</td>
<td align="right">0.3303785</td>
<td align="right">-2.5478863</td>
<td align="right">0.0108378</td>
</tr>
<tr class="even">
<td align="left">typeWater Park</td>
<td align="right">-0.5368024</td>
<td align="right">0.2900213</td>
<td align="right">-1.8509072</td>
<td align="right">0.0641829</td>
</tr>
<tr class="odd">
<td align="left">regionEMEA</td>
<td align="right">-0.7424560</td>
<td align="right">0.3419614</td>
<td align="right">-2.1711691</td>
<td align="right">0.0299184</td>
</tr>
<tr class="even">
<td align="left">regionEurope Middle East Africa</td>
<td align="right">-0.0950834</td>
<td align="right">0.3875865</td>
<td align="right">-0.2453216</td>
<td align="right">0.8062074</td>
</tr>
<tr class="odd">
<td align="left">regionLatin America</td>
<td align="right">-0.8266498</td>
<td align="right">0.3715557</td>
<td align="right">-2.2248340</td>
<td align="right">0.0260924</td>
</tr>
<tr class="even">
<td align="left">regionNorth America</td>
<td align="right">-0.4789397</td>
<td align="right">0.2575723</td>
<td align="right">-1.8594381</td>
<td align="right">0.0629651</td>
</tr>
</tbody>
</table>
<pre class="r"><code>best_fit |&gt;
  broom::glance() |&gt;
  knitr::kable(caption = &quot;Table.3 The AIC of the model&quot;)</code></pre>
<table style="width:100%;">
<caption>Table.3 The AIC of the model</caption>
<colgroup>
<col width="18%" />
<col width="10%" />
<col width="13%" />
<col width="11%" />
<col width="11%" />
<col width="11%" />
<col width="15%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">null.deviance</th>
<th align="right">df.null</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">637.5938</td>
<td align="right">590</td>
<td align="right">-312.8703</td>
<td align="right">641.7406</td>
<td align="right">676.7951</td>
<td align="right">625.7406</td>
<td align="right">583</td>
<td align="right">591</td>
</tr>
</tbody>
</table>
<p>A full logistic regression model was fitted to our data with all
Concomitant variables that we were interested in, including
<code>attendance</code>, <code>type</code>, and <code>region</code> by
<code>glm()</code> function with <code>binomial</code> as family.</p>
<p>Then forward step-wise model selection was performed by
<code>step()</code> to selected the best fitted model with lowest AIC
value.</p>
<p>After step-wise selection, we chose the full model as the final
logistic regression model while <code>attendance</code>,
<code>typeMuseum</code>, <code>regionEMEA</code> and
<code>regionLatin America</code> showed significant association with the
<code>pandemic_level</code>. As showed in Table.1, the model statement
is </p>
<p><em>pandemic_level = 2.2365446 + (-8.5e-09)attendance +
(-0.8417669)Museum + (-0.5368024)Water Park + (-0.7424560)EMEA +
(-0.0950834)Europe Middle East Africa + (-0.8266498)Latin America
+(-0.4789397)North America</em></p>
</div>
<div id="cross-validation-and-roc" class="section level4">
<h4>Cross validation and ROC</h4>
<pre class="r"><code>#cross validation 5 fold
set.seed(1)
folds &lt;- createFolds(y=pull(cv_results, pandemic_level),k=5)

#five fold ROC
auc_value&lt;-as.numeric()

for(i in 1:5){
  fold_test &lt;- cv_results[folds[[i]],] 
  fold_train &lt;- cv_results[-folds[[i]],] 
  fold_pre &lt;- glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = fold_train )
  fold_predict &lt;- predict(fold_pre,type=&#39;response&#39;,newdata=fold_test)
  auc_value&lt;- append(auc_value,as.numeric(auc(as.numeric(pull(fold_test, pandemic_level)),fold_predict)))
}


#ROC for fold 1 as example
fold_test &lt;- cv_results[folds[[1]],]
fold_train &lt;- cv_results[-folds[[1]],]

fold_pre &lt;- glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = fold_train ) 
fold_predict &lt;- predict(fold_pre,type=&#39;response&#39;,newdata=fold_test)
roc1&lt;-roc(pull(fold_test, pandemic_level),fold_predict)

plot(roc1, print.auc=T, auc.polygon=T, grid=c(0.1, 0.2),
     grid.col=c(&quot;green&quot;, &quot;red&quot;), max.auc.polygon=T,
     auc.polygon.col=&quot;skyblue&quot;, 
     print.thres=T)
mtext(&quot;Fig.3 The ROC curve for fold 1 of the model&quot;, side = 1, line = 4.1)</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-58-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>After 5 fold cross validation, the model performance was indicated by
a mean AUC value, which equals to 0.5564096, the ROC curve for fold 1
was displayed in Fig.3 as an example.</p>
</div>
<div id="disscusion" class="section level4">
<h4>Disscusion</h4>
<p>According to the results, the prediction ability of the model was not
excellent with a low AUC value, which may cause by the small sample
size. In addition, in the binary classification of dependent variables,
the sample size gap between the two categories was large, and the model
can be improved by under-sampling or over-sampling methods. Moreover,
the prediction ability of the model can be improved by adding weight
parameters when establishing the model.</p>
</div>
</div>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<div id="result-summary" class="section level3">
<h3>Result Summary</h3>
<p>Our in-depth analysis of theme park attendance involved the
application of linear and logistic regression models, exploratory data
analysis, and ANOVA tests. The linear regression delved into the
connection between attendance and diverse predictors, including city,
country, year, type, and region. This examination unearthed significant
associations between attendance and specific cities, countries, years,
park types, and regions. Subsequently, we implemented multiple linear
regression, incorporating variables that we interested in, with stepwise
regression fine-tuning the model. </p>
<p>The logistic regression model introduced a new variable,
<code>pandemic_level</code>, reflecting different stages of the COVID-19
pandemic. This logistic regression model successfully identified
noteworthy associations between attendance, park type, region, and the
pandemic level. Our analytical progress encompassed data preparation,
cross-validation, ROC curve visualization, and detailed discussions on
model performance. Descriptive analyses provided concise summaries of
attendance trends categorized by type, region, and country, offering
valuable insights into the global landscape of theme park attendance.
</p>
<p>Moreover, ANOVA tests were employed to rigorously evaluate the
significance of mean differences in attendance across various types and
years. This comprehensive analysis seamlessly integrated statistical
techniques and visualization, resulting in a thorough exploration of the
theme park dataset.</p>
</div>
<div id="discussion-1" class="section level3">
<h3>Discussion</h3>
<p>Furthermore, there are still many limitations in our study, such as
small sample size and insufficient sample level, which may lead to
unclear trends of park flow in different regions or types during
visualization, as well as low sensitivity of regression models. </p>
<p>In future studies, other factors that may be related to the flow of
visitors to theme parks, such as park size, opening policies, and annual
income of facilities, can be added, in order to further explore the
overall impact of the epidemic on theme parks. At the same time,
under-sampling or over-sampling methods can be applied to improve the
balance of data, which may improve the prediction ability and accuracy
of the regression models.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
