---
title: "Logistic Regression"
author: "Peng Su"
date: "2023-12-05"
output: github_document
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(modelr)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 9, 
  fig.height = 6,
  out.width = "90%",
	fig.align = 'center'
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
park_df =
  read_csv("ultimate data.csv") |>
  janitor::clean_names() |>
  drop_na()

logistic_df = 
  park_df |>
  mutate(
    type = as.factor(type),
    region = as.factor(region),
    country = as.factor(country),
    pandemic_level = case_when(
      year == 2019 ~ "outbreak",
      year == 2020 ~ "outbreak",
      year == 2021 ~ "outbreak",
      year == 2022 ~ "control"
    ),
    pandemic_level = as.factor(pandemic_level)
  ) 

```


```{r}
table(logistic_df$pandemic_level)

logistic_df |>
  ggplot(aes(park_name, log10(attendance), color = pandemic_level)) +
  geom_point(alpha = .7) +
  facet_grid(. ~ region )

logistic_df |>
  filter(region == "Asia Pacific") |>
  ggplot(aes(park_name, log10(attendance), color = pandemic_level)) +
  geom_point(alpha = .7) +
  facet_grid(. ~ country)
```



```{r}
cv_results = 
  crossv_mc(
  logistic_df,
  n = 10,
  test = 0.2,
  id = ".id"
)

cv_df =
  cv_results |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

test

```{r}
colnames(logistic_df)
cv_df = 
  cv_df |> 
  mutate(
    attend_mod  = map(train, \(df) glm(pandemic_level ~ attendance, family = "binomial", data = df)),
    attend_type_mod  = map(train, \(df) glm(pandemic_level ~ attendance + type , family = "binomial", data = df)),
    attend_type_region  = map(train, \(df) glm(pandemic_level ~ attendance + type + region , family = "binomial", data = df))
    ) |> 
  mutate(
    rmse_attend = map2_dbl(attend_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_type = map2_dbl(attend_type_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_region = map2_dbl(attend_type_region, test, \(mod, df) rmse(model = mod, data = df)))
```


test
先不分region，去除worldwide
看图选region

```{r}
# 使用glm()函数进行逻辑回归
model <- glm(Flow ~ ParkType + YearType, data = data, family = "binomial")
colnames(logistic_df)

test1 = logistic_df |>
  filter(region == "Asia Pacific")

logistic_df$region
model =  glm(pandemic_level ~ attendance  , family = "binomial", data =logistic_df)
summary(model)
model =  glm(pandemic_level ~ attendance + type , family = "binomial", data =logistic_df)
summary(model)
model =  glm(pandemic_level ~ attendance + type + country, family = "binomial", data =logistic_df)
summary(model)
# 查看模型摘要
summary(model)
```


```{r}
# 使用glm()函数进行逻辑回归
model <- glm(Flow ~ ParkType + YearType, data = data, family = "binomial")
colnames(logistic_df)

test1 = logistic_df |>
  filter(region == "Asia Pacific")

logistic_df$region
model =  glm(pandemic_level ~ attendance  , family = "binomial", data =test1)
summary(model)
model =  glm(pandemic_level ~ attendance + type , family = "binomial", data =test1)
summary(model)
model =  glm(pandemic_level ~ attendance + type + country, family = "binomial", data =test1)
summary(model)
# 查看模型摘要
summary(model)

```



