<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Peng Su, Jixin Li" />


<title>Regression</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="Data-Collection_Updated.html">Data Collection</a>
</li>
<li>
  <a href="theme_zz.html">EDA</a>
</li>
<li>
  <a href="Regression.html">Regression</a>
</li>
<li>
  <a href="mailto:&lt;you@youremail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/&lt;YOUR_GH_NAME&gt;/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Regression</h1>
<h4 class="author">Peng Su, Jixin Li</h4>

</div>


<div id="linear-regression" class="section level1">
<h1>Linear Regression</h1>
<p>Linear regression is used to model the relationship between
attendance and five independent variables (city, country, year, type,
and region). It assumes that this relationship is linear, meaning
changes in the predictors are associated with a constant change in the
response. We first fit linear regression of each predictors to check if
they are associated with attendance.</p>
<div id="relationship-between-city-and-attendance"
class="section level2">
<h2>Relationship between city and attendance</h2>
<p><img src="Regression_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>a few cities are associated with attendance such as ANAHEIM, Beijing,
UNIVERSAL CITY, TOKYO, VATICAN. In general, there is no apparent linear
relationship between city and attendance.</p>
</div>
<div id="relationship-between-country-and-attendance"
class="section level2">
<h2>Relationship between country and attendance</h2>
<p><img src="Regression_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>only one country Japan is significantly associated with attendance.
In general, there is no apparent linear relationship between country and
attendance.</p>
</div>
<div id="relationship-between-year-and-attendance"
class="section level2">
<h2>Relationship between year and attendance</h2>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year, data = data_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -22189468 -14873528  -8200722   4982092 184429278 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6104922321 1747418850   3.494 0.000505 ***
## year          -3011254     864862  -3.482 0.000527 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.6e+07 on 738 degrees of freedom
## Multiple R-squared:  0.01616,    Adjusted R-squared:  0.01483 
## F-statistic: 12.12 on 1 and 738 DF,  p-value: 0.0005274</code></pre>
<p>according to the summary of linear regression, <span
class="math inline">\(\widehat{Y}=\widehat{\beta_0}+\widehat{\beta_1}*X\)</span>.
Linear Model: <span
class="math inline">\(\widehat{attendance}=6104922321-3011254*year\)</span>.</p>
<p><img src="Regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Year is significantly associated with attendance, and there is a
linear relationship between year and attendance. Attendance has
experienced a decline from 2019 to 2022.</p>
</div>
<div id="relationship-between-park-type-and-attendance"
class="section level2">
<h2>Relationship between park type and attendance</h2>
<p><img src="Regression_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Park type is significantly associated with attendance.
Amusement/Theme Park has the highest attendance and water park has the
lowest attendance.</p>
</div>
<div id="relationship-between-region-and-attendance"
class="section level2">
<h2>Relationship between region and attendance</h2>
<p><img src="Regression_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Latin America is significantly associated with attendance. Overall,
there is no apparent linear relationship between region and
attendance.</p>
</div>
<div id="fit-a-multiple-linear-regression" class="section level2">
<h2>Fit a Multiple linear regression</h2>
<p>Multiple linear regression allows us to account for the influence of
multiple independent variables on the attendance simultaneously. The
outcomes of the linear regression analysis suggest that the variable
“year” exhibits a linear relationship with attendance. Additionally,
specific categories within the “type” and “region” variables are found
to be significantly associated with attendance. Thus, variables “year”,
“type”, and “region” are used to fit a multiple linear regression.</p>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year + type + region, data = data_df)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -45964074 -11813664  -4985390   6989976 161399771 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                     4621928259 1470060108   3.144  0.00173 ** 
## year                              -2266156     727662  -3.114  0.00192 ** 
## typeMuseum                       -28938548    2387097 -12.123  &lt; 2e-16 ***
## typeWater Park                   -31241190    1983579 -15.750  &lt; 2e-16 ***
## regionEMEA                       -14707744    2635034  -5.582 3.36e-08 ***
## regionEurope Middle East Africa    9197198    3154499   2.916  0.00366 ** 
## regionLatin America              -19240504    2955262  -6.511 1.39e-10 ***
## regionNorth America                1670022    2040565   0.818  0.41339    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21800000 on 732 degrees of freedom
## Multiple R-squared:  0.3141, Adjusted R-squared:  0.3075 
## F-statistic: 47.88 on 7 and 732 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>only North America within region is not significantly associated with
attendance.</p>
</div>
<div id="stepwise-regression" class="section level2">
<h2>Stepwise regression</h2>
<p>stepwise regression helps streamline the modeling process by
automatically including or excluding variables based on statistical
criteria. We use both backward and forward selection to find the best
fit model.</p>
<pre><code>## Start:  AIC=25016.07
## attendance ~ year + type + region
## 
##          Df  Sum of Sq        RSS   AIC
## &lt;none&gt;                 3.4784e+17 25016
## - year    1 4.6088e+15 3.5245e+17 25024
## - region  4 4.0930e+16 3.8877e+17 25090
## - type    2 1.3329e+17 4.8113e+17 25252</code></pre>
<pre><code>## 
## Call:
## lm(formula = attendance ~ year + type + region, data = data_df)
## 
## Coefficients:
##                     (Intercept)                             year  
##                      4621928259                         -2266156  
##                      typeMuseum                   typeWater Park  
##                       -28938548                        -31241190  
##                      regionEMEA  regionEurope Middle East Africa  
##                       -14707744                          9197198  
##             regionLatin America              regionNorth America  
##                       -19240504                          1670022</code></pre>
<p>The best fit model with lowest AIC is <span
class="math inline">\(\widehat{attendance}=\widehat{\beta_0}+\widehat{\beta_1}*year+\widehat{\beta_2}*type+\widehat{\beta_3}*region\)</span>.</p>
</div>
</div>
<div id="logistic-regression" class="section level1">
<h1>Logistic Regression</h1>
<div id="background" class="section level2">
<h2>Background</h2>
<p>In order to further study the relationship between different stages
of the COVID-19 pandemic and the visitor flow of the theme park, based
on the development process of the pandemic, the years from 2019 to 2022
are divided into two pandemic levels</p>
<ul>
<li><p>Outbreak period: 2019 to 2021</p></li>
<li><p>Control period: 2022</p></li>
</ul>
<p>Then add to our data as <code>pandemic_level</code>.</p>
<p>Furthermore, to classify the pandemic period by park attendance and
other covariates, including Park Type and Region, we established a
logistic regression model with <code>pandemic_level</code> as the
dependent variable.</p>
</div>
<div id="data-preparation" class="section level2">
<h2>Data Preparation</h2>
<pre class="r"><code>#import the data and tidy
set.seed(12138)

park_df =
  read_csv(&quot;ultimate data.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  drop_na()

logistic_df = 
  park_df |&gt;
  mutate(
    type = as.factor(type),
    region = as.factor(region),
    country = as.factor(country),
    pandemic_level = case_when(
      year == 2019 ~ &quot;outbreak&quot;,
      year == 2020 ~ &quot;outbreak&quot;,
      year == 2021 ~ &quot;outbreak&quot;,
      year == 2022 ~ &quot;control&quot;
    ),
    pandemic_level = as.factor(pandemic_level)
  ) </code></pre>
<pre class="r"><code>#attendance relationship
logistic_df |&gt;
  ggplot(aes(park_name, log10(attendance), color = pandemic_level)) +
  geom_point(alpha = .7) +
  facet_grid(. ~ region ) +
  labs(x = &quot;Parks&quot;, y = &quot;Attendance (log10)&quot;,
       caption = &quot;Fig.1 The relationship between park attendance and pandemic level across regions&quot;) +
  theme(axis.text.x = element_blank() )</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-16-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#split data into train and test subset
cv_results = 
  logistic_df |&gt;
  filter(region != &quot;Worldwide&quot;) |&gt;
  mutate(
    pandemic_level = 
      case_match(
        pandemic_level,
        &quot;outbreak&quot; ~ 1,
        &quot;control&quot; ~ 0
      )
  )

cv_df = 
  crossv_mc(
  cv_results,1
)

cv_df =
  cv_df |&gt; 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))</code></pre>
<p>After transforming attendance by log function, the relationship
between the park attendance an the pandemic levels was displayed in
Fig.1.</p>
<p>It can be noticed that different epidemic stages may have different
visitor flow patterns, in other words, the traffic of theme parks from
2019 to 2022 can be classified according to the extent of the epidemic.
This is particularly true in EMEA, the Middle East and Latin
America.</p>
<p>Then the observations in region <em>“Worldwide”</em> were excluded as
redundant data and <code>pandemic_level</code> is converted to a
binomial distribution in order to fit logistic regression models and
predict epidemic levels more easily.</p>
</div>
<div id="logistic-model" class="section level2">
<h2>Logistic model</h2>
<pre class="r"><code>#fit model and selection
log_mod =  
  cv_df |&gt;
  select(train) |&gt;
  unnest(cols = c(train)) |&gt;
  glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = _)

step(log_mod, direction = &quot;forward&quot;) 

best_fit = log_mod</code></pre>
<pre class="r"><code>#model summary
coef(best_fit) |&gt;
  knitr::kable(col.names = c(&quot;Variables&quot; , &quot;Coefficients&quot;),
               caption = &quot;Table.1 The coefficients of model&quot;)</code></pre>
<table>
<caption>Table.1 The coefficients of model</caption>
<thead>
<tr class="header">
<th align="left">Variables</th>
<th align="right">Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2.2365446</td>
</tr>
<tr class="even">
<td align="left">attendance</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">typeMuseum</td>
<td align="right">-0.8417669</td>
</tr>
<tr class="even">
<td align="left">typeWater Park</td>
<td align="right">-0.5368024</td>
</tr>
<tr class="odd">
<td align="left">regionEMEA</td>
<td align="right">-0.7424560</td>
</tr>
<tr class="even">
<td align="left">regionEurope Middle East Africa</td>
<td align="right">-0.0950834</td>
</tr>
<tr class="odd">
<td align="left">regionLatin America</td>
<td align="right">-0.8266498</td>
</tr>
<tr class="even">
<td align="left">regionNorth America</td>
<td align="right">-0.4789397</td>
</tr>
</tbody>
</table>
<pre class="r"><code>best_fit |&gt;
  broom::tidy() |&gt;
  knitr::kable(caption = &quot;Table.2 Summary of the chose model&quot; )</code></pre>
<table>
<caption>Table.2 Summary of the chose model</caption>
<colgroup>
<col width="43%" />
<col width="14%" />
<col width="13%" />
<col width="14%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2.2365446</td>
<td align="right">0.3397519</td>
<td align="right">6.5828760</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">attendance</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
<td align="right">-2.0617899</td>
<td align="right">0.0392277</td>
</tr>
<tr class="odd">
<td align="left">typeMuseum</td>
<td align="right">-0.8417669</td>
<td align="right">0.3303785</td>
<td align="right">-2.5478863</td>
<td align="right">0.0108378</td>
</tr>
<tr class="even">
<td align="left">typeWater Park</td>
<td align="right">-0.5368024</td>
<td align="right">0.2900213</td>
<td align="right">-1.8509072</td>
<td align="right">0.0641829</td>
</tr>
<tr class="odd">
<td align="left">regionEMEA</td>
<td align="right">-0.7424560</td>
<td align="right">0.3419614</td>
<td align="right">-2.1711691</td>
<td align="right">0.0299184</td>
</tr>
<tr class="even">
<td align="left">regionEurope Middle East Africa</td>
<td align="right">-0.0950834</td>
<td align="right">0.3875865</td>
<td align="right">-0.2453216</td>
<td align="right">0.8062074</td>
</tr>
<tr class="odd">
<td align="left">regionLatin America</td>
<td align="right">-0.8266498</td>
<td align="right">0.3715557</td>
<td align="right">-2.2248340</td>
<td align="right">0.0260924</td>
</tr>
<tr class="even">
<td align="left">regionNorth America</td>
<td align="right">-0.4789397</td>
<td align="right">0.2575723</td>
<td align="right">-1.8594381</td>
<td align="right">0.0629651</td>
</tr>
</tbody>
</table>
<pre class="r"><code>best_fit |&gt;
  broom::glance() |&gt;
  knitr::kable(caption = &quot;Table.3 The AIC of the model&quot;)</code></pre>
<table style="width:100%;">
<caption>Table.3 The AIC of the model</caption>
<colgroup>
<col width="18%" />
<col width="10%" />
<col width="13%" />
<col width="11%" />
<col width="11%" />
<col width="11%" />
<col width="15%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">null.deviance</th>
<th align="right">df.null</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">637.5938</td>
<td align="right">590</td>
<td align="right">-312.8703</td>
<td align="right">641.7406</td>
<td align="right">676.7951</td>
<td align="right">625.7406</td>
<td align="right">583</td>
<td align="right">591</td>
</tr>
</tbody>
</table>
<p>A full logistic regression model was fitted to our data with all
Concomitant variables that we were interested in, including
<code>attendance</code>, <code>type</code>, and <code>region</code> by
<code>glm()</code> function with <code>binomial</code> as family.</p>
<p>Then forward step-wise model selection was performed by
<code>step()</code> to selected the best fitted model with lowest AIC
value.</p>
<p>After step-wise selection, we chose the full model as the final
logistic regression model while <code>attendance</code>,
<code>typeMuseum</code>, <code>regionEMEA</code> and
<code>regionLatin America</code> showed significant association with the
<code>pandemic_level</code>. As showed in Table.1, the model statement
is </p>
<p><em>pandemic_level = 2.2365446 + (-8.5e-09)attendance +
(-0.8417669)Museum + (-0.5368024)Water Park + (-0.7424560)EMEA +
(-0.0950834)Europe Middle East Africa + (-0.8266498)Latin America
+(-0.4789397)North America</em></p>
</div>
<div id="cross-validation-and-roc" class="section level2">
<h2>Cross validation and ROC</h2>
<pre class="r"><code>#cross validation 5 fold
set.seed(1)
folds &lt;- createFolds(y=pull(cv_results, pandemic_level),k=5)

#five fold ROC
auc_value&lt;-as.numeric()

for(i in 1:5){
  fold_test &lt;- cv_results[folds[[i]],] 
  fold_train &lt;- cv_results[-folds[[i]],] 
  fold_pre &lt;- glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = fold_train )
  fold_predict &lt;- predict(fold_pre,type=&#39;response&#39;,newdata=fold_test)
  auc_value&lt;- append(auc_value,as.numeric(auc(as.numeric(pull(fold_test, pandemic_level)),fold_predict)))
}


#ROC for fold 1 as example
fold_test &lt;- cv_results[folds[[1]],]
fold_train &lt;- cv_results[-folds[[1]],]

fold_pre &lt;- glm(pandemic_level ~ attendance + type + region, family = &quot;binomial&quot;, data = fold_train ) 
fold_predict &lt;- predict(fold_pre,type=&#39;response&#39;,newdata=fold_test)
roc1&lt;-roc(pull(fold_test, pandemic_level),fold_predict)

plot(roc1, print.auc=T, auc.polygon=T, grid=c(0.1, 0.2),
     grid.col=c(&quot;green&quot;, &quot;red&quot;), max.auc.polygon=T,
     auc.polygon.col=&quot;skyblue&quot;, 
     print.thres=T)
mtext(&quot;Fig.3 The ROC curve for fold 1 of the model&quot;, side = 1, line = 4.1)</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-20-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>After 5 fold cross validation, the model performance was indicated by
a mean AUC value, which equals to 0.5564096, the ROC curve for fold 1
was displayed in Fig.3 as an example.</p>
</div>
<div id="disscusion" class="section level2">
<h2>Disscusion</h2>
<p>According to the results, the prediction ability of the model was not
excellent with a low AUC value, which may cause by the small sample
size. In addition, in the binary classification of dependent variables,
the sample size gap between the two categories was large, and the model
can be improved by under-sampling or over-sampling methods. Moreover,
the prediction ability of the model can be improved by adding weight
parameters when establishing the model.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
