---
title: "theme_zz3168"
author: "Zixuan Zhang"
date: "2023-12-05"
output: html_document
---
```{r}
library(tidyverse)
library(plotly)
```


```{r}
theme_full = 
  read_csv("ultimate data.csv")
```

Top 20 theme park from worldwide's sum attendance by different country.
```{r}
#| echo: false
#| message: false
theme_full|> 
  filter(Region == "Worldwide") |> 
  group_by(Country) |> 
  summarise(sumattand = sum(Attendance)) |> 
  plot_ly(x = ~ Country, y = ~ sumattand, color = ~ Country, type = "bar", colors = "viridis", alpha = 0.5) 
```


```{r}

```

anova test by year between 2019 to 2022
$$H_0: \mu_{\text{2019}} = \mu_{\text{2020}} = \mu_{\text{2021}}= \mu_{\text{2022}} ~~ \text{vs} ~~ H_1: \text{at least two means are not equal}$$
```{r}

dat = 
  theme_full |> 
  filter(
    Region != c("Worldwide")
    ) |> 
  mutate(
    Year = as.factor(Year)
  ) 

anova2 = aov(Attendance ~ Year , data = dat) |> 
  summary()

```
With a p-value of less than 2e-16, we would reject the null hypothesis. We have evidence that at least two of the means are not equal. Meaning the mean attendance among year groups is different for at least two groups.
